DROP table if EXISTS hits;
CREATE TABLE hits
(
    WatchID BIGINT NOT NULL,
    JavaEnable INT NOT NULL,
    Title TEXT NOT NULL,
    GoodEvent INT NOT NULL,
    EventTime timestamptz NOT NULL,
    EventDate timestamptz NOT NULL,
    CounterID INT NOT NULL,
    ClientIP INT NOT NULL,
    RegionID INT NOT NULL,
    UserID BIGINT NOT NULL,
    CounterClass INT NOT NULL,
    OS INT NOT NULL,
    UserAgent INT NOT NULL,
    URL TEXT NOT NULL,
    Referer TEXT NOT NULL,
    Refresh INT NOT NULL,
    RefererCategoryID INT NOT NULL,
    RefererRegionID INT NOT NULL,
    URLCategoryID INT NOT NULL,
    URLRegionID INT NOT NULL,
    ResolutionWidth INT NOT NULL,
    ResolutionHeight INT NOT NULL,
    ResolutionDepth INT NOT NULL,
    FlashMajor INT NOT NULL,
    FlashMinor INT NOT NULL,
    FlashMinor2 TEXT NOT NULL,
    NetMajor INT NOT NULL,
    NetMinor INT NOT NULL,
    UserAgentMajor INT NOT NULL,
    UserAgentMinor TEXT NOT NULL,
    CookieEnable INT NOT NULL,
    JavascriptEnable INT NOT NULL,
    IsMobile INT NOT NULL,
    MobilePhone INT NOT NULL,
    MobilePhoneModel TEXT NOT NULL,
    Params TEXT NOT NULL,
    IPNetworkID INT NOT NULL,
    TraficSourceID INT NOT NULL,
    SearchEngineID INT NOT NULL,
    SearchPhrase TEXT NOT NULL,
    AdvEngineID INT NOT NULL,
    IsArtifical INT NOT NULL,
    WindowClientWidth INT NOT NULL,
    WindowClientHeight INT NOT NULL,
    ClientTimeZone INT NOT NULL,
    ClientEventTime timestamptz NOT NULL,
    SilverlightVersion1 INT NOT NULL,
    SilverlightVersion2 INT NOT NULL,
    SilverlightVersion3 INT NOT NULL,
    SilverlightVersion4 INT NOT NULL,
    PageCharset TEXT NOT NULL,
    CodeVersion INT NOT NULL,
    IsLink INT NOT NULL,
    IsDownload INT NOT NULL,
    IsNotBounce INT NOT NULL,
    FUniqID BIGINT NOT NULL,
    OriginalURL TEXT NOT NULL,
    HID INT NOT NULL,
    IsOldCounter INT NOT NULL,
    IsEvent INT NOT NULL,
    IsParameter INT NOT NULL,
    DontCountHits INT NOT NULL,
    WithHash INT NOT NULL,
    HitColor TEXT NOT NULL,
    LocalEventTime timestamptz NOT NULL,
    Age INT NOT NULL,
    Sex INT NOT NULL,
    Income INT NOT NULL,
    Interests INT NOT NULL,
    Robotness INT NOT NULL,
    RemoteIP INT NOT NULL,
    WindowName INT NOT NULL,
    OpenerName INT NOT NULL,
    HistoryLength INT NOT NULL,
    BrowserLanguage TEXT NOT NULL,
    BrowserCountry TEXT NOT NULL,
    SocialNetwork TEXT NOT NULL,
    SocialAction TEXT NOT NULL,
    HTTPError INT NOT NULL,
    SendTiming INT NOT NULL,
    DNSTiming INT NOT NULL,
    ConnectTiming INT NOT NULL,
    ResponseStartTiming INT NOT NULL,
    ResponseEndTiming INT NOT NULL,
    FetchTiming INT NOT NULL,
    SocialSourceNetworkID INT NOT NULL,
    SocialSourcePage TEXT NOT NULL,
    ParamPrice BIGINT NOT NULL,
    ParamOrderID TEXT NOT NULL,
    ParamCurrency TEXT NOT NULL,
    ParamCurrencyID INT NOT NULL,
    OpenstatServiceName TEXT NOT NULL,
    OpenstatCampaignID TEXT NOT NULL,
    OpenstatAdID TEXT NOT NULL,
    OpenstatSourceID TEXT NOT NULL,
    UTMSource TEXT NOT NULL,
    UTMMedium TEXT NOT NULL,
    UTMCampaign TEXT NOT NULL,
    UTMContent TEXT NOT NULL,
    UTMTerm TEXT NOT NULL,
    FromTag TEXT NOT NULL,
    HasGCLID INT NOT NULL,
    RefererHash BIGINT NOT NULL,
    URLHash BIGINT NOT NULL,
    CLID INT NOT NULL,
    PRIMARY KEY (
        CounterID, 
        EventDate, 
        UserID, 
        EventTime, 
        WatchID
    )
) WITH (
    distribution_key='UserID',
    segment_key='EventTime',
    clustering_key='CounterID,EventDate,UserID,EventTime,WatchID',
    bitmap_columns='advengineid, counterid, isrefresh, isdownload, islink,refererhash,dontcounthits,urlhash'
);