#!/bin/bash
set -eu

MYSQL_RUN="sudo docker run -i --rm --network host mysql:5 \
    mysql --host 127.0.0.1 --port 5029 --user=root --password=mypass"

$MYSQL_RUN -e "DROP DATABASE IF EXISTS test"
$MYSQL_RUN -e "CREATE DATABASE test"
$MYSQL_RUN --database=test -e "$(cat create.sql)"

# Infobright errors out on row 93557187 in the full dataset; truncate.
head -n 90000000 hits.tsv > hits90m.tsv

sudo docker run -i --rm --volume "$(pwd):/workdir" --network host mysql:5 \
    mysql --host 127.0.0.1 --port 5029 --user=root --password=mypass --database=test \
    -e "SET sql_log_bin = 0;
        LOAD DATA LOCAL INFILE '/workdir/hits90m.tsv' INTO TABLE test.hits
        FIELDS TERMINATED BY '\t' ENCLOSED BY '' ESCAPED BY '\\\\' LINES TERMINATED BY '\n' STARTING BY ''"

rm -f hits.tsv hits90m.tsv
sync
