#!/bin/bash
set -eu

export PGCLIENTENCODING=UTF8

mkdir -p data
# Symlink rather than copy: hits.csv is 75 GB.
sudo ln -sf "$PWD/hits.csv" data/hits.csv

PGPASSWORD=oxla psql -h localhost -U oxla -q -t < create.sql
PGPASSWORD=oxla psql -h localhost -U oxla -q -t -c "COPY hits FROM '/data/hits.csv';"

sudo rm -f data/hits.csv
sync
