#!/bin/bash
set -eu

export PGCLIENTENCODING=UTF8

mkdir -p data
sudo mv hits.csv data/

PGPASSWORD=oxla psql -h localhost -U oxla -q -t < create.sql
PGPASSWORD=oxla psql -h localhost -U oxla -q -t -c "COPY hits FROM '/data/hits.csv';"

sudo rm -f data/hits.csv
sync
