#!/usr/bin/env bash
# ==============================================================================
# SILICIUM CLICKBENCH HARNESS — START (IN-PROCESS EMBEDDED ENGINE)
# License: SCSL-1.0 / MIT Evaluation License
# ==============================================================================
exit 0
