#!/bin/bash
set -e

if [ ! -x vortex-datafusion-cli/target/release/vortex-datafusion-cli ]; then
    # <vortex-version>-<datafusion-version>
    CLI_TAG=0.70.0-53.1.0

    if ! command -v cargo >/dev/null 2>&1; then
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > rust-init.sh
        bash rust-init.sh -y
    fi
    export HOME=${HOME:=~}
    # shellcheck disable=SC1091
    source "$HOME/.cargo/env"

    if [ "$(free -g | awk '/^Mem:/{print $2}')" -lt 12 ]; then
        if [ "$(swapon --noheadings --show | wc -l)" -eq 0 ]; then
            sudo fallocate -l 8G /swapfile
            sudo chmod 600 /swapfile
            sudo mkswap /swapfile
            sudo swapon /swapfile
        fi
    fi

    sudo apt-get update -y
    sudo apt-get install -y build-essential clang cmake git libclang-dev pkg-config

    if [ ! -d vortex-datafusion-cli ]; then
        git clone https://github.com/vortex-data/vortex-datafusion-cli.git
    fi
    cd vortex-datafusion-cli
    git fetch --tags
    git checkout "$CLI_TAG"
    CARGO_PROFILE_RELEASE_LTO=true RUSTFLAGS="-C codegen-units=1" \
        cargo build --release --bin vortex-datafusion-cli
fi
