len(read(["CounterID"]))
len(read(["AdvEngineID"], Q()[col("AdvEngineID") != 0]))
let(read(["AdvEngineID", "ResolutionWidth"]), lambda d: (d["AdvEngineID"].sum(), len(d), d["ResolutionWidth"].mean()))
read(["UserID"])["UserID"].mean()
read(["UserID"])["UserID"].nunique()
read(["SearchPhrase"])["SearchPhrase"].nunique()
let(read(["EventDate"])["EventDate"], lambda s: (s.min(), s.max()))
read(query=Q()[col("AdvEngineID") != 0].groupby("AdvEngineID").agg({"c": ("CounterID", "count")})).sort_values("c", ascending=False)
read(["RegionID", "UserID"]).groupby("RegionID")["UserID"].nunique().nlargest(10)
read(["RegionID", "AdvEngineID", "ResolutionWidth", "UserID"]).groupby("RegionID").agg(s=("AdvEngineID", "sum"), c=("UserID", "size"), w=("ResolutionWidth", "mean"), u=("UserID", "nunique")).nlargest(10, "c")
read(["MobilePhoneModel", "UserID"], Q()[col("MobilePhoneModel") != ""]).groupby("MobilePhoneModel")["UserID"].nunique().nlargest(10)
read(["MobilePhone", "MobilePhoneModel", "UserID"], Q()[col("MobilePhoneModel") != ""]).groupby(["MobilePhone", "MobilePhoneModel"])["UserID"].nunique().nlargest(10)
read(query=Q()[col("SearchPhrase") != ""].groupby("SearchPhrase").agg({"c": ("CounterID", "count")})).nlargest(10, "c")
read(["SearchPhrase", "UserID"], Q()[col("SearchPhrase") != ""]).groupby("SearchPhrase")["UserID"].nunique().nlargest(10)
read(["SearchEngineID", "SearchPhrase"], Q()[col("SearchPhrase") != ""]).groupby(["SearchEngineID", "SearchPhrase"]).size().nlargest(10)
read(query=Q().groupby("UserID").agg({"c": ("CounterID", "count")})).nlargest(10, "c")
read(["UserID", "SearchPhrase"]).groupby(["UserID", "SearchPhrase"]).size().nlargest(10)
read(["UserID", "SearchPhrase"]).groupby(["UserID", "SearchPhrase"]).size().head(10)
let(read(["UserID", "EventTime", "SearchPhrase"]), lambda d: d.groupby([d["UserID"], d["EventTime"].dt.minute, d["SearchPhrase"]]).size().nlargest(10))
read(["UserID"], Q()[col("UserID") == 435090932899640449])
len(read(["URL"], Q()[col("URL").regex_match("google")]))
read(["SearchPhrase", "URL"], Q()[col("URL").regex_match("google") & (col("SearchPhrase") != "")]).groupby("SearchPhrase").agg(u=("URL", "min"), c=("URL", "size")).nlargest(10, "c")
read(["SearchPhrase", "URL", "Title", "UserID"], Q()[col("Title").regex_match("Google") & ~col("URL").regex_match("\\.google\\.") & (col("SearchPhrase") != "")]).groupby("SearchPhrase").agg(u=("URL", "min"), t=("Title", "min"), c=("URL", "size"), d=("UserID", "nunique")).nlargest(10, "c")
read(None, Q()[col("URL").regex_match("google")]).nsmallest(10, "EventTime")
read(["SearchPhrase", "EventTime"], Q()[col("SearchPhrase") != ""]).nsmallest(10, "EventTime")[["SearchPhrase"]]
read(["SearchPhrase"], Q()[col("SearchPhrase") != ""]).sort_values("SearchPhrase").head(10)
read(["SearchPhrase", "EventTime"], Q()[col("SearchPhrase") != ""]).sort_values(["EventTime", "SearchPhrase"]).head(10)[["SearchPhrase"]]
let(read(["CounterID", "URL"], Q()[col("URL") != ""]), lambda d: d.assign(l=d["URL"].str.len()).groupby("CounterID").agg(l=("l", "mean"), c=("l", "size")).loc[lambda x: x["c"] > 100000].nlargest(25, "l"))
let(read(["Referer"], Q()[col("Referer") != ""]), lambda d: d.assign(k=d["Referer"].str.replace(r"^https?://(?:www\.)?([^/]+)/.*$", r"\1", regex=True, flags=re.DOTALL), l=d["Referer"].str.len()).groupby("k").agg(l=("l", "mean"), c=("l", "size"), m=("Referer", "min")).loc[lambda x: x["c"] > 100000].nlargest(25, "l"))
let(read(["ResolutionWidth"])["ResolutionWidth"], lambda s: tuple(int((s + i).sum()) for i in range(90)))
read(["SearchEngineID", "ClientIP", "IsRefresh", "ResolutionWidth"], Q()[col("SearchPhrase") != ""]).groupby(["SearchEngineID", "ClientIP"]).agg(c=("IsRefresh", "size"), r=("IsRefresh", "sum"), w=("ResolutionWidth", "mean")).nlargest(10, "c")
read(["WatchID", "ClientIP", "IsRefresh", "ResolutionWidth"], Q()[col("SearchPhrase") != ""]).groupby(["WatchID", "ClientIP"]).agg(c=("IsRefresh", "size"), r=("IsRefresh", "sum"), w=("ResolutionWidth", "mean")).nlargest(10, "c")
read(["WatchID", "ClientIP", "IsRefresh", "ResolutionWidth"]).groupby(["WatchID", "ClientIP"]).agg(c=("IsRefresh", "size"), r=("IsRefresh", "sum"), w=("ResolutionWidth", "mean")).nlargest(10, "c")
read(query=Q().groupby("URL").agg({"c": ("CounterID", "count")})).nlargest(10, "c")
read(query=Q().groupby("URL").agg({"c": ("CounterID", "count")})).nlargest(10, "c").reset_index().assign(one=1)[["one", "URL", "c"]]
let(read(["ClientIP"])["ClientIP"], lambda s: pd.DataFrame({"ClientIP": s, "m1": s - 1, "m2": s - 2, "m3": s - 3}).groupby(["ClientIP", "m1", "m2", "m3"]).size().nlargest(10))
read(query=Q()[(col("CounterID") == 62) & (col("EventDate") >= pd.Timestamp("2013-07-01")) & (col("EventDate") <= pd.Timestamp("2013-07-31")) & (col("DontCountHits") == 0) & (col("IsRefresh") == 0) & (col("URL") != "")].groupby("URL").agg({"PageViews": ("CounterID", "count")})).nlargest(10, "PageViews")
read(query=Q()[(col("CounterID") == 62) & (col("EventDate") >= pd.Timestamp("2013-07-01")) & (col("EventDate") <= pd.Timestamp("2013-07-31")) & (col("DontCountHits") == 0) & (col("IsRefresh") == 0) & (col("Title") != "")].groupby("Title").agg({"PageViews": ("CounterID", "count")})).nlargest(10, "PageViews")
read(query=Q()[(col("CounterID") == 62) & (col("EventDate") >= pd.Timestamp("2013-07-01")) & (col("EventDate") <= pd.Timestamp("2013-07-31")) & (col("IsRefresh") == 0) & (col("IsLink") != 0) & (col("IsDownload") == 0)].groupby("URL").agg({"PageViews": ("CounterID", "count")})).nlargest(1010, "PageViews").iloc[1000:1010]
let(read(["TraficSourceID", "SearchEngineID", "AdvEngineID", "Referer", "URL"], Q()[(col("CounterID") == 62) & (col("EventDate") >= pd.Timestamp("2013-07-01")) & (col("EventDate") <= pd.Timestamp("2013-07-31")) & (col("IsRefresh") == 0)]), lambda d: d.assign(Src=d["Referer"].where((d["SearchEngineID"] == 0) & (d["AdvEngineID"] == 0), "")).groupby(["TraficSourceID", "SearchEngineID", "AdvEngineID", "Src", "URL"]).size().nlargest(1010).iloc[1000:1010])
read(["URLHash", "EventDate"], Q()[(col("CounterID") == 62) & (col("EventDate") >= pd.Timestamp("2013-07-01")) & (col("EventDate") <= pd.Timestamp("2013-07-31")) & (col("IsRefresh") == 0) & col("TraficSourceID").isin(-1, 6) & (col("RefererHash") == 3594120000172545465)]).groupby(["URLHash", "EventDate"]).size().nlargest(110).iloc[100:110]
read(["WindowClientWidth", "WindowClientHeight"], Q()[(col("CounterID") == 62) & (col("EventDate") >= pd.Timestamp("2013-07-01")) & (col("EventDate") <= pd.Timestamp("2013-07-31")) & (col("IsRefresh") == 0) & (col("DontCountHits") == 0) & (col("URLHash") == 2868770270353813622)]).groupby(["WindowClientWidth", "WindowClientHeight"]).size().nlargest(10010).iloc[10000:10010]
let(read(["EventTime"], Q()[(col("CounterID") == 62) & (col("EventDate") >= pd.Timestamp("2013-07-14")) & (col("EventDate") <= pd.Timestamp("2013-07-15")) & (col("IsRefresh") == 0) & (col("DontCountHits") == 0)]), lambda d: d["EventTime"].dt.floor("min").value_counts().sort_index().iloc[1000:1010])
