DROP DATABASE IF EXISTS hits;
CREATE DATABASE hits;
-- The parquet files store EventTime as raw INT64 epoch seconds and EventDate
-- as raw INT32 epoch days (no parquet logical types), so the view converts
-- them to DATETIME/DATE — otherwise predicates like EventDate >= '2013-07-14'
-- silently match nothing. Same fixup as duckdb-parquet's make_date/toDateTime.
-- Unlike the single hits.parquet, the partitioned files also lack the String
-- annotation on their BYTE_ARRAY columns, so those infer as VARBINARY and
-- string queries fail ("Error statistic type : varbinary") — cast them back
-- to VARCHAR (duckdb-parquet's binary_as_string equivalent).
CREATE VIEW hits.hits AS
SELECT
    WatchID,
    JavaEnable,
    CAST(Title AS VARCHAR) AS Title,
    GoodEvent,
    CAST(from_unixtime(EventTime) AS DATETIME) AS EventTime,
    CAST(days_add('1970-01-01', EventDate) AS DATE) AS EventDate,
    CounterID,
    ClientIP,
    RegionID,
    UserID,
    CounterClass,
    OS,
    UserAgent,
    CAST(URL AS VARCHAR) AS URL,
    CAST(Referer AS VARCHAR) AS Referer,
    IsRefresh,
    RefererCategoryID,
    RefererRegionID,
    URLCategoryID,
    URLRegionID,
    ResolutionWidth,
    ResolutionHeight,
    ResolutionDepth,
    FlashMajor,
    FlashMinor,
    CAST(FlashMinor2 AS VARCHAR) AS FlashMinor2,
    NetMajor,
    NetMinor,
    UserAgentMajor,
    CAST(UserAgentMinor AS VARCHAR) AS UserAgentMinor,
    CookieEnable,
    JavascriptEnable,
    IsMobile,
    MobilePhone,
    CAST(MobilePhoneModel AS VARCHAR) AS MobilePhoneModel,
    CAST(Params AS VARCHAR) AS Params,
    IPNetworkID,
    TraficSourceID,
    SearchEngineID,
    CAST(SearchPhrase AS VARCHAR) AS SearchPhrase,
    AdvEngineID,
    IsArtifical,
    WindowClientWidth,
    WindowClientHeight,
    ClientTimeZone,
    ClientEventTime,
    SilverlightVersion1,
    SilverlightVersion2,
    SilverlightVersion3,
    SilverlightVersion4,
    CAST(PageCharset AS VARCHAR) AS PageCharset,
    CodeVersion,
    IsLink,
    IsDownload,
    IsNotBounce,
    FUniqID,
    CAST(OriginalURL AS VARCHAR) AS OriginalURL,
    HID,
    IsOldCounter,
    IsEvent,
    IsParameter,
    DontCountHits,
    WithHash,
    CAST(HitColor AS VARCHAR) AS HitColor,
    LocalEventTime,
    Age,
    Sex,
    Income,
    Interests,
    Robotness,
    RemoteIP,
    WindowName,
    OpenerName,
    HistoryLength,
    CAST(BrowserLanguage AS VARCHAR) AS BrowserLanguage,
    CAST(BrowserCountry AS VARCHAR) AS BrowserCountry,
    CAST(SocialNetwork AS VARCHAR) AS SocialNetwork,
    CAST(SocialAction AS VARCHAR) AS SocialAction,
    HTTPError,
    SendTiming,
    DNSTiming,
    ConnectTiming,
    ResponseStartTiming,
    ResponseEndTiming,
    FetchTiming,
    SocialSourceNetworkID,
    CAST(SocialSourcePage AS VARCHAR) AS SocialSourcePage,
    ParamPrice,
    CAST(ParamOrderID AS VARCHAR) AS ParamOrderID,
    CAST(ParamCurrency AS VARCHAR) AS ParamCurrency,
    ParamCurrencyID,
    CAST(OpenstatServiceName AS VARCHAR) AS OpenstatServiceName,
    CAST(OpenstatCampaignID AS VARCHAR) AS OpenstatCampaignID,
    CAST(OpenstatAdID AS VARCHAR) AS OpenstatAdID,
    CAST(OpenstatSourceID AS VARCHAR) AS OpenstatSourceID,
    CAST(UTMSource AS VARCHAR) AS UTMSource,
    CAST(UTMMedium AS VARCHAR) AS UTMMedium,
    CAST(UTMCampaign AS VARCHAR) AS UTMCampaign,
    CAST(UTMContent AS VARCHAR) AS UTMContent,
    CAST(UTMTerm AS VARCHAR) AS UTMTerm,
    CAST(FromTag AS VARCHAR) AS FromTag,
    HasGCLID,
    RefererHash,
    URLHash,
    CLID
FROM FILES(
    "path" = "file://__DATA_DIR__/hits_*.parquet",
    "format" = "parquet"
);
