#!/bin/bash
set -eu

sudo systemctl start cedardb.service

# On multi-NUMA systems stay within one node for better performance.
numa_nodes=$(ls -d /sys/devices/system/node/node* 2>/dev/null | wc -l)
if [ "${numa_nodes}" -gt 1 ]; then
    parallel=$(cat /sys/devices/system/node/node0/cpulist \
        | tr ',' '\n' \
        | awk -F'-' '{if(NF==2) s+=($2-$1+1); else s+=1} END{print s}')
    until psql -c "SET debug.parallel = ${parallel};" >/dev/null 2>&1; do sleep 1; done
fi