#!/bin/bash
set -eu

if PGPASSWORD=postgres psql -p 5432 -h 127.0.0.1 -U postgres -c 'SELECT 1' >/dev/null 2>&1; then
    exit 0
fi

# Disable asynchronous IO, the EBS GP2 device provides only 250 MiB/s. Therefore,
# async IO is not needed to exploit the full bandwidth.
sudo docker run -d --name umbradb \
    -v "$(pwd)/db:/var/db" \
    -v "$(pwd)/data:/data" \
    -p 5432:5432 \
    --privileged \
    --ulimit nofile=1048576:1048576 \
    --ulimit memlock=-1:-1 \
    -e ASYNCIO=0 \
    umbradb/umbra:latest >/dev/null
