drop view IF EXISTS hits;

CREATE VIEW hits AS
SELECT
    CounterID,
    CAST(EventDate as DATE) EventDate,
    UserID,
    CAST(EventTime as DateTime) EventTime,
    WatchID,
    JavaEnable,
    CAST(Title as TEXT) Title,
    GoodEvent,
    ClientIP,
    RegionID,
    CounterClass,
    OS,
    UserAgent,
    CAST(`URL` as TEXT) `URL`,
    CAST(Referer as TEXT) Referer,
    IsRefresh,
    RefererCategoryID,
    RefererRegionID,
    URLCategoryID,
    URLRegionID,
    ResolutionWidth,
    ResolutionHeight,
    ResolutionDepth,
    FlashMajor,
    FlashMinor,
    FlashMinor2,
    NetMajor,
    NetMinor,
    UserAgentMajor,
    CAST(UserAgentMinor as VARCHAR(255)) as UserAgentMinor,
    CookieEnable,
    JavascriptEnable,
    IsMobile,
    MobilePhone,
    CAST(MobilePhoneModel as TEXT) MobilePhoneModel,
    CAST(Params as TEXT) Params,
    IPNetworkID,
    TraficSourceID,
    SearchEngineID,
    CAST(SearchPhrase as TEXT) SearchPhrase,
    AdvEngineID,
    IsArtifical,
    WindowClientWidth,
    WindowClientHeight,
    ClientTimeZone,
    ClientEventTime,
    SilverlightVersion1,
    SilverlightVersion2,
    SilverlightVersion3,
    SilverlightVersion4,
    CAST(PageCharset as TEXT) PageCharset,
    CodeVersion,
    IsLink,
    IsDownload,
    IsNotBounce,
    FUniqID,
    CAST(OriginalURL AS TEXT) OriginalURL,
    HID,
    IsOldCounter,
    IsEvent,
    IsParameter,
    DontCountHits,
    WithHash,
    CAST(HitColor as TEXT) HitColor,
    LocalEventTime,
    Age,
    Sex,
    Income,
    Interests,
    Robotness,
    RemoteIP,
    WindowName,
    OpenerName,
    HistoryLength,
    CAST(BrowserLanguage as TEXT) BrowserLanguage,
    CAST(BrowserCountry as TEXT) BrowserCountry,
    CAST(SocialNetwork as TEXT) SocialNetwork,
    CAST(SocialAction as TEXT) SocialAction,
    HTTPError,
    SendTiming,
    DNSTiming,
    ConnectTiming,
    ResponseStartTiming,
    ResponseEndTiming,
    FetchTiming,
    SocialSourceNetworkID,
    CAST(SocialSourcePage as TEXT) SocialSourcePage,
    ParamPrice,
    CAST(ParamOrderID as TEXT) ParamOrderID,
    CAST(ParamCurrency as TEXT) ParamCurrency,
    ParamCurrencyID,
    CAST(OpenstatServiceName as TEXT) OpenstatServiceName,
    CAST(OpenstatCampaignID as TEXT) OpenstatCampaignID,
    CAST(OpenstatAdID as TEXT) OpenstatAdID,
    CAST(OpenstatSourceID as TEXT) OpenstatSourceID,
    CAST(UTMSource as TEXT) UTMSource,
    CAST(UTMMedium as TEXT) UTMMedium,
    CAST(UTMCampaign as TEXT) UTMCampaign,
    CAST(UTMContent as TEXT) UTMContent,
    CAST(UTMTerm as TEXT) UTMTerm,
    CAST(FromTag as TEXT) FromTag,
    HasGCLID,
    RefererHash,
    URLHash,
    CLID
FROM
    FILES(
        "path" = "file:///home/ubuntu/ClickBench/starrocks-parquet/StarRocks/be/hits_*.parquet",
        "format" = "parquet"
    );