#!/bin/bash
set -e

sudo apt-get update -y
sudo apt-get install -y python3-pip python3-venv openjdk-17-jdk

if [ ! -d myenv ]; then
    python3 -m venv myenv
fi
# shellcheck disable=SC1091
source myenv/bin/activate
pip install -q pyspark==4.0.0 psutil
