CREATE SCHEMA IF NOT EXISTS hive.clickbench;

CREATE TABLE hive.clickbench.hits_raw (
    WatchID bigint,
    JavaEnable smallint,
    Title varchar,
    GoodEvent smallint,
    EventTime bigint,
    EventDate integer,
    CounterID integer,
    ClientIP integer,
    RegionID integer,
    UserID bigint,
    CounterClass smallint,
    OS smallint,
    UserAgent smallint,
    URL varchar,
    Referer varchar,
    IsRefresh smallint,
    RefererCategoryID smallint,
    RefererRegionID integer,
    URLCategoryID smallint,
    URLRegionID integer,
    ResolutionWidth smallint,
    ResolutionHeight smallint,
    ResolutionDepth smallint,
    FlashMajor smallint,
    FlashMinor smallint,
    FlashMinor2 varchar,
    NetMajor smallint,
    NetMinor smallint,
    UserAgentMajor smallint,
    UserAgentMinor varchar,
    CookieEnable smallint,
    JavascriptEnable smallint,
    IsMobile smallint,
    MobilePhone smallint,
    MobilePhoneModel varchar,
    Params varchar,
    IPNetworkID integer,
    TraficSourceID smallint,
    SearchEngineID smallint,
    SearchPhrase varchar,
    AdvEngineID smallint,
    IsArtifical smallint,
    WindowClientWidth smallint,
    WindowClientHeight smallint,
    ClientTimeZone smallint,
    ClientEventTime bigint,
    SilverlightVersion1 smallint,
    SilverlightVersion2 smallint,
    SilverlightVersion3 integer,
    SilverlightVersion4 smallint,
    PageCharset varchar,
    CodeVersion integer,
    IsLink smallint,
    IsDownload smallint,
    IsNotBounce smallint,
    FUniqID bigint,
    OriginalURL varchar,
    HID integer,
    IsOldCounter smallint,
    IsEvent smallint,
    IsParameter smallint,
    DontCountHits smallint,
    WithHash smallint,
    HitColor varchar,
    LocalEventTime bigint,
    Age smallint,
    Sex smallint,
    Income smallint,
    Interests smallint,
    Robotness smallint,
    RemoteIP integer,
    WindowName integer,
    OpenerName integer,
    HistoryLength smallint,
    BrowserLanguage varchar,
    BrowserCountry varchar,
    SocialNetwork varchar,
    SocialAction varchar,
    HTTPError smallint,
    SendTiming integer,
    DNSTiming integer,
    ConnectTiming integer,
    ResponseStartTiming integer,
    ResponseEndTiming integer,
    FetchTiming integer,
    SocialSourceNetworkID smallint,
    SocialSourcePage varchar,
    ParamPrice bigint,
    ParamOrderID varchar,
    ParamCurrency varchar,
    ParamCurrencyID smallint,
    OpenstatServiceName varchar,
    OpenstatCampaignID varchar,
    OpenstatAdID varchar,
    OpenstatSourceID varchar,
    UTMSource varchar,
    UTMMedium varchar,
    UTMCampaign varchar,
    UTMContent varchar,
    UTMTerm varchar,
    FromTag varchar,
    HasGCLID smallint,
    RefererHash bigint,
    URLHash bigint,
    CLID integer
)
WITH (
    external_location = 'file:///clickbench/hits',
    format = 'PARQUET'
);

-- The Parquet files store EventTime/ClientEventTime/LocalEventTime as Unix epoch BIGINT
-- and EventDate as a UINT16 day count from 1970-01-01. The view exposes the canonical
-- ClickBench column types so queries.sql matches the standard text.
CREATE VIEW hive.clickbench.hits AS
SELECT
    WatchID, JavaEnable, Title, GoodEvent,
    from_unixtime(EventTime) AS EventTime,
    date_add('day', EventDate, DATE '1970-01-01') AS EventDate,
    CounterID, ClientIP, RegionID, UserID, CounterClass, OS, UserAgent,
    URL, Referer, IsRefresh, RefererCategoryID, RefererRegionID,
    URLCategoryID, URLRegionID, ResolutionWidth, ResolutionHeight,
    ResolutionDepth, FlashMajor, FlashMinor, FlashMinor2, NetMajor, NetMinor,
    UserAgentMajor, UserAgentMinor, CookieEnable, JavascriptEnable,
    IsMobile, MobilePhone, MobilePhoneModel, Params, IPNetworkID,
    TraficSourceID, SearchEngineID, SearchPhrase, AdvEngineID, IsArtifical,
    WindowClientWidth, WindowClientHeight, ClientTimeZone,
    from_unixtime(ClientEventTime) AS ClientEventTime,
    SilverlightVersion1, SilverlightVersion2, SilverlightVersion3,
    SilverlightVersion4, PageCharset, CodeVersion, IsLink, IsDownload,
    IsNotBounce, FUniqID, OriginalURL, HID, IsOldCounter, IsEvent,
    IsParameter, DontCountHits, WithHash, HitColor,
    from_unixtime(LocalEventTime) AS LocalEventTime,
    Age, Sex, Income, Interests, Robotness, RemoteIP, WindowName,
    OpenerName, HistoryLength, BrowserLanguage, BrowserCountry,
    SocialNetwork, SocialAction, HTTPError, SendTiming, DNSTiming,
    ConnectTiming, ResponseStartTiming, ResponseEndTiming, FetchTiming,
    SocialSourceNetworkID, SocialSourcePage, ParamPrice, ParamOrderID,
    ParamCurrency, ParamCurrencyID, OpenstatServiceName, OpenstatCampaignID,
    OpenstatAdID, OpenstatSourceID, UTMSource, UTMMedium, UTMCampaign,
    UTMContent, UTMTerm, FromTag, HasGCLID, RefererHash, URLHash, CLID
FROM hive.clickbench.hits_raw;
