CREATE EXTENSION IF NOT EXISTS pg_duckdb;

CREATE SCHEMA IF NOT EXISTS clickbench;

DROP VIEW IF EXISTS hits_parquet;

CREATE VIEW hits_parquet AS
SELECT
  r['WatchID'] WatchID,
  r['JavaEnable'] JavaEnable,
  r['Title'] Title,
  r['GoodEvent'] GoodEvent,
  'epoch'::timestamp +(r['EventTime'] || 'second')::interval EventTime,
  'epoch'::timestamp +(r['EventDate'] || 'day')::interval EventDate,
  r['CounterID'] CounterID,
  r['ClientIP'] ClientIP,
  r['RegionID'] RegionID,
  r['UserID'] UserID,
  r['CounterClass'] CounterClass,
  r['OS'] OS,
  r['UserAgent'] UserAgent,
  r['URL'] URL,
  r['Referer'] Referer,
  r['Refresh'] Refresh,
  r['RefererCategoryID'] RefererCategoryID,
  r['RefererRegionID'] RefererRegionID,
  r['URLCategoryID'] URLCategoryID,
  r['URLRegionID'] URLRegionID,
  r['ResolutionWidth'] ResolutionWidth,
  r['ResolutionHeight'] ResolutionHeight,
  r['ResolutionDepth'] ResolutionDepth,
  r['FlashMajor'] FlashMajor,
  r['FlashMinor'] FlashMinor,
  r['FlashMinor2'] FlashMinor2,
  r['NetMajor'] NetMajor,
  r['NetMinor'] NetMinor,
  r['UserAgentMajor'] UserAgentMajor,
  r['UserAgentMinor'] UserAgentMinor,
  r['CookieEnable'] CookieEnable,
  r['JavascriptEnable'] JavascriptEnable,
  r['IsMobile'] IsMobile,
  r['MobilePhone'] MobilePhone,
  r['MobilePhoneModel'] MobilePhoneModel,
  r['Params'] Params,
  r['IPNetworkID'] IPNetworkID,
  r['TraficSourceID'] TraficSourceID,
  r['SearchEngineID'] SearchEngineID,
  r['SearchPhrase'] SearchPhrase,
  r['AdvEngineID'] AdvEngineID,
  r['IsArtifical'] IsArtifical,
  r['WindowClientWidth'] WindowClientWidth,
  r['WindowClientHeight'] WindowClientHeight,
  r['ClientTimeZone'] ClientTimeZone,
  'epoch'::timestamp +(r['ClientEventTime'] || 'second')::interval ClientEventTime,
  r['SilverlightVersion1'] SilverlightVersion1,
  r['SilverlightVersion2'] SilverlightVersion2,
  r['SilverlightVersion3'] SilverlightVersion3,
  r['SilverlightVersion4'] SilverlightVersion4,
  r['PageCharset'] PageCharset,
  r['CodeVersion'] CodeVersion,
  r['IsLink'] IsLink,
  r['IsDownload'] IsDownload,
  r['IsNotBounce'] IsNotBounce,
  r['FUniqID'] FUniqID,
  r['OriginalURL'] OriginalURL,
  r['HID'] HID,
  r['IsOldCounter'] IsOldCounter,
  r['IsEvent'] IsEvent,
  r['IsParameter'] IsParameter,
  r['DontCountHits'] DontCountHits,
  r['WithHash'] WithHash,
  r['HitColor'] HitColor,
  'epoch'::timestamp +(r['LocalEventTime'] || 'second')::interval LocalEventTime,
  r['Age'] Age,
  r['Sex'] Sex,
  r['Income'] Income,
  r['Interests'] Interests,
  r['Robotness'] Robotness,
  r['RemoteIP'] RemoteIP,
  r['WindowName'] WindowName,
  r['OpenerName'] OpenerName,
  r['HistoryLength'] HistoryLength,
  r['BrowserLanguage'] BrowserLanguage,
  r['BrowserCountry'] BrowserCountry,
  r['SocialNetwork'] SocialNetwork,
  r['SocialAction'] SocialAction,
  r['HTTPError'] HTTPError,
  r['SendTiming'] SendTiming,
  r['DNSTiming'] DNSTiming,
  r['ConnectTiming'] ConnectTiming,
  r['ResponseStartTiming'] ResponseStartTiming,
  r['ResponseEndTiming'] ResponseEndTiming,
  r['FetchTiming'] FetchTiming,
  r['SocialSourceNetworkID'] SocialSourceNetworkID,
  r['SocialSourcePage'] SocialSourcePage,
  r['ParamPrice'] ParamPrice,
  r['ParamOrderID'] ParamOrderID,
  r['ParamCurrency'] ParamCurrency,
  r['ParamCurrencyID'] ParamCurrencyID,
  r['OpenstatServiceName'] OpenstatServiceName,
  r['OpenstatCampaignID'] OpenstatCampaignID,
  r['OpenstatAdID'] OpenstatAdID,
  r['OpenstatSourceID'] OpenstatSourceID,
  r['UTMSource'] UTMSource,
  r['UTMMedium'] UTMMedium,
  r['UTMCampaign'] UTMCampaign,
  r['UTMContent'] UTMContent,
  r['UTMTerm'] UTMTerm,
  r['FromTag'] FromTag,
  r['HasGCLID'] HasGCLID,
  r['RefererHash'] RefererHash,
  r['URLHash'] URLHash,
  r['CLID'] CLID
FROM
  read_parquet('/tmp/hits.parquet') r;

DROP TABLE IF EXISTS clickbench.hits;

CREATE TABLE clickbench.hits
USING duckdb AS
SELECT
  *
FROM
  hits_parquet;
