hits.select(pl.len()).collect().item()
hits.filter(pl.col('AdvEngineID') != 0).select(pl.len()).collect().item()
hits.select(a_sum=pl.col('AdvEngineID').sum(), count=pl.len(), a_mean=pl.col('ResolutionWidth').mean()).collect().rows()[0]
hits.select(pl.col('UserID').mean()).collect().item()
hits.select(pl.col('UserID').n_unique()).collect().item()
hits.select(pl.col('SearchPhrase').n_unique()).collect().item()
hits.select(e_min=pl.col('EventDate').min(), e_max=pl.col('EventDate').max()).collect().rows()[0]
hits.filter(pl.col('AdvEngineID') != 0).group_by('AdvEngineID').agg(pl.len().alias('count')).sort('count', descending=True).collect()
hits.group_by('RegionID').agg(pl.col('UserID').n_unique().alias('u')).sort('u', descending=True).head(10).collect()
hits.group_by('RegionID').agg([pl.sum('AdvEngineID').alias('AdvEngineID_sum'), pl.len().alias('count'), pl.mean('ResolutionWidth').alias('ResolutionWidth_mean'), pl.col('UserID').n_unique().alias('UserID_nunique')]).sort('count', descending=True).head(10).collect()
hits.filter(pl.col('MobilePhoneModel') != '').group_by('MobilePhoneModel').agg(pl.col('UserID').n_unique()).sort('UserID', descending=True).head(10).collect()
hits.filter(pl.col('MobilePhoneModel') != '').group_by(['MobilePhone', 'MobilePhoneModel']).agg(pl.col('UserID').n_unique()).sort('UserID', descending=True).head(10).collect()
hits.filter(pl.col('SearchPhrase') != '').group_by('SearchPhrase').agg(pl.len().alias('count')).sort('count', descending=True).head(10).collect()
hits.filter(pl.col('SearchPhrase') != '').group_by('SearchPhrase').agg(pl.col('UserID').n_unique()).sort('UserID', descending=True).head(10).collect()
hits.filter(pl.col('SearchPhrase') != '').group_by(['SearchEngineID', 'SearchPhrase']).agg(pl.len().alias('count')).sort('count', descending=True).head(10).collect()
hits.group_by('UserID').agg(pl.len().alias('count')).sort('count', descending=True).head(10).collect()
hits.group_by(['UserID', 'SearchPhrase']).agg(pl.len().alias('count')).sort('count', descending=True).head(10).collect()
hits.group_by(['UserID', 'SearchPhrase']).agg(pl.len()).head(10).collect()
hits.group_by([pl.col('UserID'), pl.col('EventTime').dt.minute(), 'SearchPhrase']).agg(pl.len().alias('count')).sort('count', descending=True).head(10).collect()
hits.select('UserID').filter(pl.col('UserID') == 435090932899640449).collect()
hits.filter(pl.col('URL').str.contains('google')).select(pl.len()).collect().item()
hits.filter(pl.col('URL').str.contains('google') & (pl.col('SearchPhrase') != '')).group_by('SearchPhrase').agg([pl.col('URL').min(), pl.len().alias('count')]).sort('count', descending=True).head(10).collect()
hits.filter(pl.col('Title').str.contains('Google') & ~pl.col('URL').str.contains('.google.') & (pl.col('SearchPhrase') != '')).group_by('SearchPhrase').agg([pl.col('URL').min(), pl.col('Title').min(), pl.len().alias('count'), pl.col('UserID').n_unique()]).sort('count', descending=True).head(10).collect()
hits.filter(pl.col('URL').str.contains('google')).sort('EventTime').head(10).collect()
hits.filter(pl.col('SearchPhrase') != '').sort('EventTime').select('SearchPhrase').head(10).collect()
hits.filter(pl.col('SearchPhrase') != '').sort('SearchPhrase').select('SearchPhrase').head(10).collect()
hits.filter(pl.col('SearchPhrase') != '').sort(['EventTime', 'SearchPhrase']).select('SearchPhrase').head(10).collect()
hits.filter(pl.col('URL') != '').group_by('CounterID').agg([pl.col('URL').str.len_chars().mean().alias('l'), pl.len().alias('c')]).filter(pl.col('c') > 100000).sort('l', descending=True).limit(25).collect()
hits.filter(pl.col('Referer') != '').with_columns(pl.col('Referer').str.extract('^https?://(?:www\\.)?([^/]+)/.*$').alias('k')).group_by('k').agg([pl.col('Referer').str.len_chars().mean().alias('l'), pl.col('Referer').min().alias('min_referer'), pl.len().alias('c')]).filter(pl.col('c') > 100000).sort('l', descending=True).limit(25).collect()
hits.select([(pl.col('ResolutionWidth') + i).sum().alias(f'c_{i}') for i in range(90)]).collect()
hits.filter(pl.col('SearchPhrase') != '').group_by(['SearchEngineID', 'ClientIP']).agg([pl.len().alias('c'), pl.sum('IsRefresh').alias('IsRefreshSum'), pl.mean('ResolutionWidth').alias('AvgResolutionWidth')]).sort('c', descending=True).head(10).collect()
hits.filter(pl.col('SearchPhrase') != '').group_by(['WatchID', 'ClientIP']).agg([pl.len().alias('c'), pl.sum('IsRefresh').alias('IsRefreshSum'), pl.mean('ResolutionWidth').alias('AvgResolutionWidth')]).sort('c', descending=True).head(10).collect()
hits.group_by(['WatchID', 'ClientIP']).agg([pl.len().alias('c'), pl.sum('IsRefresh').alias('IsRefreshSum'), pl.mean('ResolutionWidth').alias('AvgResolutionWidth')]).sort('c', descending=True).head(10).collect()
hits.group_by('URL').agg(pl.len().alias('c')).sort('c', descending=True).head(10).collect()
hits.group_by('URL').agg(pl.len().alias('c')).sort('c', descending=True).with_columns(pl.lit(1).alias('1')).head(10).collect()
hits.group_by('ClientIP').agg(pl.len().alias('c')).with_columns([(pl.col('ClientIP') - 1).alias('ClientIP_minus_1'), (pl.col('ClientIP') - 2).alias('ClientIP_minus_2'), (pl.col('ClientIP') - 3).alias('ClientIP_minus_3')]).sort('c', descending=True).head(10).collect()
hits.filter((pl.col('CounterID') == 62) & (pl.col('EventDate') >= date(2013, 7, 1)) & (pl.col('EventDate') <= date(2013, 7, 31)) & (pl.col('DontCountHits') == 0) & (pl.col('IsRefresh') == 0) & (pl.col('URL') != '')).group_by('URL').agg(pl.len().alias('PageViews')).sort('PageViews', descending=True).head(10).collect()
hits.filter((pl.col('CounterID') == 62) & (pl.col('EventDate') >= date(2013, 7, 1)) & (pl.col('EventDate') <= date(2013, 7, 31)) & (pl.col('DontCountHits') == 0) & (pl.col('IsRefresh') == 0) & (pl.col('Title') != '')).group_by('Title').agg(pl.len().alias('PageViews')).sort('PageViews', descending=True).head(10).collect()
hits.filter((pl.col('CounterID') == 62) & (pl.col('EventDate') >= date(2013, 7, 1)) & (pl.col('EventDate') <= date(2013, 7, 31)) & (pl.col('IsRefresh') == 0) & (pl.col('IsLink') != 0) & (pl.col('IsDownload') == 0)).group_by('URL').agg(pl.len().alias('PageViews')).sort('PageViews', descending=True).slice(1000, 10).collect()
hits.filter((pl.col('CounterID') == 62) & (pl.col('EventDate') >= date(2013, 7, 1)) & (pl.col('EventDate') <= date(2013, 7, 31)) & (pl.col('IsRefresh') == 0)).with_columns(pl.when(pl.col('SearchEngineID').eq(0) & pl.col('AdvEngineID').eq(0)).then(pl.col('Referer')).otherwise(pl.lit('')).alias('Src')).group_by(['TraficSourceID', 'SearchEngineID', 'AdvEngineID', 'Src', 'URL']).agg(pl.len().alias('PageViews')).sort('PageViews', descending=True).slice(1000, 10).collect()
hits.filter((pl.col('CounterID') == 62) & (pl.col('EventDate') >= date(2013, 7, 1)) & (pl.col('EventDate') <= date(2013, 7, 31)) & (pl.col('IsRefresh') == 0) & pl.col('TraficSourceID').is_in([-1, 6]) & (pl.col('RefererHash') == 3594120000172545465)).group_by(['URLHash', 'EventDate']).agg(pl.len().alias('PageViews')).sort('PageViews', descending=True).slice(100, 10).collect()
hits.filter((pl.col('CounterID') == 62) & (pl.col('EventDate') >= date(2013, 7, 1)) & (pl.col('EventDate') <= date(2013, 7, 31)) & (pl.col('IsRefresh') == 0) & (pl.col('DontCountHits') == 0) & (pl.col('URLHash') == 2868770270353813622)).group_by(['WindowClientWidth', 'WindowClientHeight']).agg(pl.len().alias('PageViews')).sort('PageViews', descending=True).slice(10000, 10).collect()
hits.filter((pl.col('CounterID') == 62) & (pl.col('EventDate') >= date(2013, 7, 14)) & (pl.col('EventDate') <= date(2013, 7, 15)) & (pl.col('IsRefresh') == 0) & (pl.col('DontCountHits') == 0)).group_by(pl.col('EventTime').dt.truncate('1m').alias('M')).agg(pl.len().alias('PageViews')).sort('M').slice(1000, 10).collect()
