-- Changes compared to '../clickhouse/create.sql':
-- * Use type INTEGER instead of SMALLINT.
-- * Use the Parquet file.
-- * Transform DATE and TIMESTAMP columns from type INTEGER in the Parquet file to type DATE and TIMESTAMP.
CREATE EXTERNAL TABLE hits_external
(
    "WatchID" BIGINT NOT NULL,
    "JavaEnable" INTEGER NOT NULL,
    "Title" TEXT NOT NULL,
    "GoodEvent" INTEGER NOT NULL,
    "EventTime" BIGINT NOT NULL,
    "EventDate" INTEGER NOT NULL,
    "CounterID" INTEGER NOT NULL,
    "ClientIP" INTEGER NOT NULL,
    "RegionID" INTEGER NOT NULL,
    "UserID" BIGINT NOT NULL,
    "CounterClass" INTEGER NOT NULL,
    "OS" INTEGER NOT NULL,
    "UserAgent" INTEGER NOT NULL,
    "URL" TEXT NOT NULL,
    "Referer" TEXT NOT NULL,
    "IsRefresh" INTEGER NOT NULL,
    "RefererCategoryID" INTEGER NOT NULL,
    "RefererRegionID" INTEGER NOT NULL,
    "URLCategoryID" INTEGER NOT NULL,
    "URLRegionID" INTEGER NOT NULL,
    "ResolutionWidth" INTEGER NOT NULL,
    "ResolutionHeight" INTEGER NOT NULL,
    "ResolutionDepth" INTEGER NOT NULL,
    "FlashMajor" INTEGER NOT NULL,
    "FlashMinor" INTEGER NOT NULL,
    "FlashMinor2" TEXT NOT NULL,
    "NetMajor" INTEGER NOT NULL,
    "NetMinor" INTEGER NOT NULL,
    "UserAgentMajor" INTEGER NOT NULL,
    "UserAgentMinor" VARCHAR(255) NOT NULL,
    "CookieEnable" INTEGER NOT NULL,
    "JavascriptEnable" INTEGER NOT NULL,
    "IsMobile" INTEGER NOT NULL,
    "MobilePhone" INTEGER NOT NULL,
    "MobilePhoneModel" TEXT NOT NULL,
    "Params" TEXT NOT NULL,
    "IPNetworkID" INTEGER NOT NULL,
    "TraficSourceID" INTEGER NOT NULL,
    "SearchEngineID" INTEGER NOT NULL,
    "SearchPhrase" TEXT NOT NULL,
    "AdvEngineID" INTEGER NOT NULL,
    "IsArtifical" INTEGER NOT NULL,
    "WindowClientWidth" INTEGER NOT NULL,
    "WindowClientHeight" INTEGER NOT NULL,
    "ClientTimeZone" INTEGER NOT NULL,
    "ClientEventTime" BIGINT NOT NULL,
    "SilverlightVersion1" INTEGER NOT NULL,
    "SilverlightVersion2" INTEGER NOT NULL,
    "SilverlightVersion3" INTEGER NOT NULL,
    "SilverlightVersion4" INTEGER NOT NULL,
    "PageCharset" TEXT NOT NULL,
    "CodeVersion" INTEGER NOT NULL,
    "IsLink" INTEGER NOT NULL,
    "IsDownload" INTEGER NOT NULL,
    "IsNotBounce" INTEGER NOT NULL,
    "FUniqID" BIGINT NOT NULL,
    "OriginalURL" TEXT NOT NULL,
    "HID" INTEGER NOT NULL,
    "IsOldCounter" INTEGER NOT NULL,
    "IsEvent" INTEGER NOT NULL,
    "IsParameter" INTEGER NOT NULL,
    "DontCountHits" INTEGER NOT NULL,
    "WithHash" INTEGER NOT NULL,
    "HitColor" CHAR NOT NULL,
    "LocalEventTime" BIGINT NOT NULL,
    "Age" INTEGER NOT NULL,
    "Sex" INTEGER NOT NULL,
    "Income" INTEGER NOT NULL,
    "Interests" INTEGER NOT NULL,
    "Robotness" INTEGER NOT NULL,
    "RemoteIP" INTEGER NOT NULL,
    "WindowName" INTEGER NOT NULL,
    "OpenerName" INTEGER NOT NULL,
    "HistoryLength" INTEGER NOT NULL,
    "BrowserLanguage" TEXT NOT NULL,
    "BrowserCountry" TEXT NOT NULL,
    "SocialNetwork" TEXT NOT NULL,
    "SocialAction" TEXT NOT NULL,
    "HTTPError" INTEGER NOT NULL,
    "SendTiming" INTEGER NOT NULL,
    "DNSTiming" INTEGER NOT NULL,
    "ConnectTiming" INTEGER NOT NULL,
    "ResponseStartTiming" INTEGER NOT NULL,
    "ResponseEndTiming" INTEGER NOT NULL,
    "FetchTiming" INTEGER NOT NULL,
    "SocialSourceNetworkID" INTEGER NOT NULL,
    "SocialSourcePage" TEXT NOT NULL,
    "ParamPrice" BIGINT NOT NULL,
    "ParamOrderID" TEXT NOT NULL,
    "ParamCurrency" TEXT NOT NULL,
    "ParamCurrencyID" INTEGER NOT NULL,
    "OpenstatServiceName" TEXT NOT NULL,
    "OpenstatCampaignID" TEXT NOT NULL,
    "OpenstatAdID" TEXT NOT NULL,
    "OpenstatSourceID" TEXT NOT NULL,
    "UTMSource" TEXT NOT NULL,
    "UTMMedium" TEXT NOT NULL,
    "UTMCampaign" TEXT NOT NULL,
    "UTMContent" TEXT NOT NULL,
    "UTMTerm" TEXT NOT NULL,
    "FromTag" TEXT NOT NULL,
    "HasGCLID" INTEGER NOT NULL,
    "RefererHash" BIGINT NOT NULL,
    "URLHash" BIGINT NOT NULL,
    "CLID" INTEGER NOT NULL
)
URL = 'file:///firebolt-core/clickbench'
OBJECT_PATTERN = 'hits.parquet'
TYPE = PARQUET;

CREATE TABLE hits
(
    WatchID BIGINT NOT NULL,
    JavaEnable INTEGER NOT NULL,
    Title TEXT NOT NULL,
    GoodEvent INTEGER NOT NULL,
    EventTime TIMESTAMP NOT NULL,
    EventDate Date NOT NULL,
    CounterID INTEGER NOT NULL,
    ClientIP INTEGER NOT NULL,
    RegionID INTEGER NOT NULL,
    UserID BIGINT NOT NULL,
    CounterClass INTEGER NOT NULL,
    OS INTEGER NOT NULL,
    UserAgent INTEGER NOT NULL,
    URL TEXT NOT NULL,
    Referer TEXT NOT NULL,
    IsRefresh INTEGER NOT NULL,
    RefererCategoryID INTEGER NOT NULL,
    RefererRegionID INTEGER NOT NULL,
    URLCategoryID INTEGER NOT NULL,
    URLRegionID INTEGER NOT NULL,
    ResolutionWidth INTEGER NOT NULL,
    ResolutionHeight INTEGER NOT NULL,
    ResolutionDepth INTEGER NOT NULL,
    FlashMajor INTEGER NOT NULL,
    FlashMinor INTEGER NOT NULL,
    FlashMinor2 TEXT NOT NULL,
    NetMajor INTEGER NOT NULL,
    NetMinor INTEGER NOT NULL,
    UserAgentMajor INTEGER NOT NULL,
    UserAgentMinor VARCHAR(255) NOT NULL,
    CookieEnable INTEGER NOT NULL,
    JavascriptEnable INTEGER NOT NULL,
    IsMobile INTEGER NOT NULL,
    MobilePhone INTEGER NOT NULL,
    MobilePhoneModel TEXT NOT NULL,
    Params TEXT NOT NULL,
    IPNetworkID INTEGER NOT NULL,
    TraficSourceID INTEGER NOT NULL,
    SearchEngineID INTEGER NOT NULL,
    SearchPhrase TEXT NOT NULL,
    AdvEngineID INTEGER NOT NULL,
    IsArtifical INTEGER NOT NULL,
    WindowClientWidth INTEGER NOT NULL,
    WindowClientHeight INTEGER NOT NULL,
    ClientTimeZone INTEGER NOT NULL,
    ClientEventTime TIMESTAMP NOT NULL,
    SilverlightVersion1 INTEGER NOT NULL,
    SilverlightVersion2 INTEGER NOT NULL,
    SilverlightVersion3 INTEGER NOT NULL,
    SilverlightVersion4 INTEGER NOT NULL,
    PageCharset TEXT NOT NULL,
    CodeVersion INTEGER NOT NULL,
    IsLink INTEGER NOT NULL,
    IsDownload INTEGER NOT NULL,
    IsNotBounce INTEGER NOT NULL,
    FUniqID BIGINT NOT NULL,
    OriginalURL TEXT NOT NULL,
    HID INTEGER NOT NULL,
    IsOldCounter INTEGER NOT NULL,
    IsEvent INTEGER NOT NULL,
    IsParameter INTEGER NOT NULL,
    DontCountHits INTEGER NOT NULL,
    WithHash INTEGER NOT NULL,
    HitColor CHAR NOT NULL,
    LocalEventTime TIMESTAMP NOT NULL,
    Age INTEGER NOT NULL,
    Sex INTEGER NOT NULL,
    Income INTEGER NOT NULL,
    Interests INTEGER NOT NULL,
    Robotness INTEGER NOT NULL,
    RemoteIP INTEGER NOT NULL,
    WindowName INTEGER NOT NULL,
    OpenerName INTEGER NOT NULL,
    HistoryLength INTEGER NOT NULL,
    BrowserLanguage TEXT NOT NULL,
    BrowserCountry TEXT NOT NULL,
    SocialNetwork TEXT NOT NULL,
    SocialAction TEXT NOT NULL,
    HTTPError INTEGER NOT NULL,
    SendTiming INTEGER NOT NULL,
    DNSTiming INTEGER NOT NULL,
    ConnectTiming INTEGER NOT NULL,
    ResponseStartTiming INTEGER NOT NULL,
    ResponseEndTiming INTEGER NOT NULL,
    FetchTiming INTEGER NOT NULL,
    SocialSourceNetworkID INTEGER NOT NULL,
    SocialSourcePage TEXT NOT NULL,
    ParamPrice BIGINT NOT NULL,
    ParamOrderID TEXT NOT NULL,
    ParamCurrency TEXT NOT NULL,
    ParamCurrencyID INTEGER NOT NULL,
    OpenstatServiceName TEXT NOT NULL,
    OpenstatCampaignID TEXT NOT NULL,
    OpenstatAdID TEXT NOT NULL,
    OpenstatSourceID TEXT NOT NULL,
    UTMSource TEXT NOT NULL,
    UTMMedium TEXT NOT NULL,
    UTMCampaign TEXT NOT NULL,
    UTMContent TEXT NOT NULL,
    UTMTerm TEXT NOT NULL,
    FromTag TEXT NOT NULL,
    HasGCLID INTEGER NOT NULL,
    RefererHash BIGINT NOT NULL,
    URLHash BIGINT NOT NULL,
    CLID INTEGER NOT NULL
) PRIMARY INDEX CounterID, EventDate, UserID, EventTime, WatchID;

INSERT INTO hits
SELECT
    "WatchID",
    "JavaEnable",
    "Title",
    "GoodEvent",
    to_timestamp("EventTime") AT TIME ZONE 'UTC' AS "EventTime",
    DATE '1970-01-01' + "EventDate" AS "EventDate",
    "CounterID",
    "ClientIP",
    "RegionID",
    "UserID",
    "CounterClass",
    "OS",
    "UserAgent",
    "URL",
    "Referer",
    "IsRefresh",
    "RefererCategoryID",
    "RefererRegionID",
    "URLCategoryID",
    "URLRegionID",
    "ResolutionWidth",
    "ResolutionHeight",
    "ResolutionDepth",
    "FlashMajor",
    "FlashMinor",
    "FlashMinor2",
    "NetMajor",
    "NetMinor",
    "UserAgentMajor",
    "UserAgentMinor",
    "CookieEnable",
    "JavascriptEnable",
    "IsMobile",
    "MobilePhone",
    "MobilePhoneModel",
    "Params",
    "IPNetworkID",
    "TraficSourceID",
    "SearchEngineID",
    "SearchPhrase",
    "AdvEngineID",
    "IsArtifical",
    "WindowClientWidth",
    "WindowClientHeight",
    "ClientTimeZone",
    to_timestamp("ClientEventTime") AT TIME ZONE 'UTC' AS "ClientEventTime",
    "SilverlightVersion1",
    "SilverlightVersion2",
    "SilverlightVersion3",
    "SilverlightVersion4",
    "PageCharset",
    "CodeVersion",
    "IsLink",
    "IsDownload",
    "IsNotBounce",
    "FUniqID",
    "OriginalURL",
    "HID",
    "IsOldCounter",
    "IsEvent",
    "IsParameter",
    "DontCountHits",
    "WithHash",
    "HitColor",
    to_timestamp("LocalEventTime") AT TIME ZONE 'UTC' AS "LocalEventTime",
    "Age",
    "Sex",
    "Income",
    "Interests",
    "Robotness",
    "RemoteIP",
    "WindowName",
    "OpenerName",
    "HistoryLength",
    "BrowserLanguage",
    "BrowserCountry",
    "SocialNetwork",
    "SocialAction",
    "HTTPError",
    "SendTiming",
    "DNSTiming",
    "ConnectTiming",
    "ResponseStartTiming",
    "ResponseEndTiming",
    "FetchTiming",
    "SocialSourceNetworkID",
    "SocialSourcePage",
    "ParamPrice",
    "ParamOrderID",
    "ParamCurrency",
    "ParamCurrencyID",
    "OpenstatServiceName",
    "OpenstatCampaignID",
    "OpenstatAdID",
    "OpenstatSourceID",
    "UTMSource",
    "UTMMedium",
    "UTMCampaign",
    "UTMContent",
    "UTMTerm",
    "FromTag",
    "HasGCLID",
    "RefererHash",
    "URLHash",
    "CLID"
FROM
    hits_external;
