#!/bin/bash
set -eu

# Installing docker.io over a docker that came from elsewhere breaks it.
if ! command -v docker >/dev/null || ! command -v jq >/dev/null; then
    sudo apt-get update -y
    sudo apt-get install -y docker.io jq
fi
sudo docker pull ghcr.io/firebolt-db/engine:dev
