-- EventQL has a sharply narrower type set than the create.sql the rest
-- of ClickBench uses: there are no signed integers (INT32/INT64 are
-- documented but rejected by the v0.4.1 parser), no TEXT/VARCHAR/CHAR,
-- and no DATE — only UINT32, UINT64, STRING, DATETIME, DOUBLE, FLOAT,
-- and BOOL.
--
-- All hits column values are non-negative in the ClickBench dataset,
-- so SMALLINT/INTEGER/BIGINT map cleanly to UINT32/UINT64. ClientIP
-- and similar columns are stored as raw 32-bit IP values (bit pattern
-- preserved as UINT32 even when the equivalent signed-int reading
-- would be negative). TEXT/VARCHAR/CHAR collapse to STRING.
-- TIMESTAMP and DATE both become DATETIME.
--
-- Identifiers: `Title` is a reserved keyword in EventQL's SQL parser
-- (T_TITLE); backticks escape it. The remaining 104 hits column names
-- are not reserved.
--
-- PRIMARY KEY is mandatory; the first column must be one of
-- STRING/UINT64/DATETIME (it doubles as the partition key). We use
-- (EventTime, WatchID).

CREATE TABLE hits (
    EventTime DATETIME NOT NULL,
    WatchID UINT64 NOT NULL,
    JavaEnable UINT32 NOT NULL,
    `Title` STRING,
    GoodEvent UINT32 NOT NULL,
    EventDate DATETIME NOT NULL,
    CounterID UINT32 NOT NULL,
    ClientIP UINT32 NOT NULL,
    RegionID UINT32 NOT NULL,
    UserID UINT64 NOT NULL,
    CounterClass UINT32 NOT NULL,
    OS UINT32 NOT NULL,
    UserAgent UINT32 NOT NULL,
    URL STRING,
    Referer STRING,
    IsRefresh UINT32 NOT NULL,
    RefererCategoryID UINT32 NOT NULL,
    RefererRegionID UINT32 NOT NULL,
    URLCategoryID UINT32 NOT NULL,
    URLRegionID UINT32 NOT NULL,
    ResolutionWidth UINT32 NOT NULL,
    ResolutionHeight UINT32 NOT NULL,
    ResolutionDepth UINT32 NOT NULL,
    FlashMajor UINT32 NOT NULL,
    FlashMinor UINT32 NOT NULL,
    FlashMinor2 STRING,
    NetMajor UINT32 NOT NULL,
    NetMinor UINT32 NOT NULL,
    UserAgentMajor UINT32 NOT NULL,
    UserAgentMinor STRING,
    CookieEnable UINT32 NOT NULL,
    JavascriptEnable UINT32 NOT NULL,
    IsMobile UINT32 NOT NULL,
    MobilePhone UINT32 NOT NULL,
    MobilePhoneModel STRING,
    Params STRING,
    IPNetworkID UINT32 NOT NULL,
    TraficSourceID UINT32 NOT NULL,
    SearchEngineID UINT32 NOT NULL,
    SearchPhrase STRING,
    AdvEngineID UINT32 NOT NULL,
    IsArtifical UINT32 NOT NULL,
    WindowClientWidth UINT32 NOT NULL,
    WindowClientHeight UINT32 NOT NULL,
    ClientTimeZone UINT32 NOT NULL,
    ClientEventTime DATETIME NOT NULL,
    SilverlightVersion1 UINT32 NOT NULL,
    SilverlightVersion2 UINT32 NOT NULL,
    SilverlightVersion3 UINT32 NOT NULL,
    SilverlightVersion4 UINT32 NOT NULL,
    PageCharset STRING,
    CodeVersion UINT32 NOT NULL,
    IsLink UINT32 NOT NULL,
    IsDownload UINT32 NOT NULL,
    IsNotBounce UINT32 NOT NULL,
    FUniqID UINT64 NOT NULL,
    OriginalURL STRING,
    HID UINT32 NOT NULL,
    IsOldCounter UINT32 NOT NULL,
    IsEvent UINT32 NOT NULL,
    IsParameter UINT32 NOT NULL,
    DontCountHits UINT32 NOT NULL,
    WithHash UINT32 NOT NULL,
    HitColor STRING NOT NULL,
    LocalEventTime DATETIME NOT NULL,
    Age UINT32 NOT NULL,
    Sex UINT32 NOT NULL,
    Income UINT32 NOT NULL,
    Interests UINT32 NOT NULL,
    Robotness UINT32 NOT NULL,
    RemoteIP UINT32 NOT NULL,
    WindowName UINT32 NOT NULL,
    OpenerName UINT32 NOT NULL,
    HistoryLength UINT32 NOT NULL,
    BrowserLanguage STRING,
    BrowserCountry STRING,
    SocialNetwork STRING,
    SocialAction STRING,
    HTTPError UINT32 NOT NULL,
    SendTiming UINT32 NOT NULL,
    DNSTiming UINT32 NOT NULL,
    ConnectTiming UINT32 NOT NULL,
    ResponseStartTiming UINT32 NOT NULL,
    ResponseEndTiming UINT32 NOT NULL,
    FetchTiming UINT32 NOT NULL,
    SocialSourceNetworkID UINT32 NOT NULL,
    SocialSourcePage STRING,
    ParamPrice UINT64 NOT NULL,
    ParamOrderID STRING,
    ParamCurrency STRING,
    ParamCurrencyID UINT32 NOT NULL,
    OpenstatServiceName STRING,
    OpenstatCampaignID STRING,
    OpenstatAdID STRING,
    OpenstatSourceID STRING,
    UTMSource STRING,
    UTMMedium STRING,
    UTMCampaign STRING,
    UTMContent STRING,
    UTMTerm STRING,
    FromTag STRING,
    HasGCLID UINT32 NOT NULL,
    RefererHash UINT64 NOT NULL,
    URLHash UINT64 NOT NULL,
    CLID UINT32 NOT NULL,
    PRIMARY KEY (EventTime, WatchID)
);
