#!/bin/bash
set -e

PINOT_VERSION=1.3.0
PINOT_DIR="apache-pinot-$PINOT_VERSION-bin"

if [ ! -d "$PINOT_DIR" ]; then
    sudo apt-get update -y
    sudo apt-get install -y openjdk-11-jdk jq

    if [ ! -f "$PINOT_DIR.tar.gz" ]; then
        wget --continue --progress=dot:giga \
            "https://downloads.apache.org/pinot/apache-pinot-$PINOT_VERSION/$PINOT_DIR.tar.gz"
    fi
    tar -zxf "$PINOT_DIR.tar.gz"
fi
