#!/bin/bash
set -e

VORTEX_VERSION=0.44.0

if ! command -v cargo >/dev/null 2>&1; then
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > rust-init.sh
    bash rust-init.sh -y
fi
export HOME=${HOME:=~}
# shellcheck disable=SC1091
source ~/.cargo/env

sudo apt-get update -y
sudo apt-get install -y gcc jq build-essential git

if [ ! -d vortex ]; then
    git clone https://github.com/spiraldb/vortex.git
fi
(
    cd vortex
    git fetch --tags
    git checkout "$VORTEX_VERSION"
    git submodule update --init
    cargo build --release --bin query_bench --package bench-vortex
)
