#!/bin/bash
set -e

# shellcheck disable=SC1091
source myenv/bin/activate

python3 - <<'PY'
from tableauhyperapi import HyperProcess, Telemetry, Connection
with HyperProcess(telemetry=Telemetry.DO_NOT_SEND_USAGE_DATA_TO_TABLEAU) as hyper:
    with Connection(hyper.endpoint) as connection:
        connection.execute_list_query("SELECT 1")
PY
