-- Auto-infer the columns from the hits.parquet
CREATE FOREIGN TABLE hits_auto () SERVER crunchy_lake_analytics OPTIONS (path 's3://clickhouse-public-datasets/hits_compatible/hits.parquet');

-- hits.parquet uses integers for date and time,
-- which most databases cannot pass directly
-- to date/time functions. Hence we convert them to date and
-- timestamptz in a view that wraps around the table
CREATE OR REPLACE VIEW hits as SELECT
  WatchID,
  JavaEnable,
  Title,
  GoodEvent,
  to_timestamp(EventTime) AS EventTime,
  to_date(EventDate) AS EventDate,
  CounterID,
  ClientIP,
  RegionID,
  UserID,
  CounterClass,
  OS,
  UserAgent,
  URL,
  Referer,
  IsRefresh,
  RefererCategoryID,
  RefererRegionID,
  URLCategoryID,
  URLRegionID,
  ResolutionWidth,
  ResolutionHeight,
  ResolutionDepth,
  FlashMajor,
  FlashMinor,
  FlashMinor2,
  NetMajor,
  NetMinor,
  UserAgentMajor,
  UserAgentMinor,
  CookieEnable,
  JavascriptEnable,
  IsMobile,
  MobilePhone,
  MobilePhoneModel,
  Params,
  IPNetworkID,
  TraficSourceID,
  SearchEngineID,
  SearchPhrase,
  AdvEngineID,
  IsArtifical,
  WindowClientWidth,
  WindowClientHeight,
  ClientTimeZone,
  ClientEventTime,
  SilverlightVersion1,
  SilverlightVersion2,
  SilverlightVersion3,
  SilverlightVersion4,
  PageCharset,
  CodeVersion,
  IsLink,
  IsDownload,
  IsNotBounce,
  FUniqID,
  OriginalURL,
  HID,
  IsOldCounter,
  IsEvent,
  IsParameter,
  DontCountHits,
  WithHash,
  HitColor,
  LocalEventTime,
  Age,
  Sex,
  Income,
  Interests,
  Robotness,
  RemoteIP,
  WindowName,
  OpenerName,
  HistoryLength,
  BrowserLanguage,
  BrowserCountry,
  SocialNetwork,
  SocialAction,
  HTTPError,
  SendTiming,
  DNSTiming,
  ConnectTiming,
  ResponseStartTiming,
  ResponseEndTiming,
  FetchTiming,
  SocialSourceNetworkID,
  SocialSourcePage,
  ParamPrice,
  ParamOrderID,
  ParamCurrency,
  ParamCurrencyID,
  OpenstatServiceName,
  OpenstatCampaignID,
  OpenstatAdID,
  OpenstatSourceID,
  UTMSource,
  UTMMedium,
  UTMCampaign,
  UTMContent,
  UTMTerm,
  FromTag,
  HasGCLID,
  RefererHash,
  URLHash,
  CLID
from hits_auto;
