-- String columns are declared NULL rather than NOT NULL because bcp's
-- character-mode default for an empty TSV field is NULL (whereas
-- Postgres COPY, MariaDB cpimport, etc. write empty strings). Forcing
-- NOT NULL here makes the bulk load fail on the first empty Title/URL/
-- SearchPhrase/... cell with SQLState 23000 "Cannot insert NULL".
-- Queries that filter with `<> ''` see NULLs as unknown (effectively
-- excluded), matching the behavior of the canonical text-empty rows.

CREATE TABLE hits
(
    WatchID BIGINT NOT NULL,
    JavaEnable SMALLINT NOT NULL,
    Title VARCHAR(MAX) NULL,
    GoodEvent SMALLINT NOT NULL,
    EventTime DATETIME2 NOT NULL,
    EventDate DATE NOT NULL,
    CounterID INT NOT NULL,
    ClientIP INT NOT NULL,
    RegionID INT NOT NULL,
    UserID BIGINT NOT NULL,
    CounterClass SMALLINT NOT NULL,
    OS SMALLINT NOT NULL,
    UserAgent SMALLINT NOT NULL,
    URL VARCHAR(MAX) NULL,
    Referer VARCHAR(MAX) NULL,
    IsRefresh SMALLINT NOT NULL,
    RefererCategoryID SMALLINT NOT NULL,
    RefererRegionID INT NOT NULL,
    URLCategoryID SMALLINT NOT NULL,
    URLRegionID INT NOT NULL,
    ResolutionWidth SMALLINT NOT NULL,
    ResolutionHeight SMALLINT NOT NULL,
    ResolutionDepth SMALLINT NOT NULL,
    FlashMajor SMALLINT NOT NULL,
    FlashMinor SMALLINT NOT NULL,
    FlashMinor2 VARCHAR(MAX) NULL,
    NetMajor SMALLINT NOT NULL,
    NetMinor SMALLINT NOT NULL,
    UserAgentMajor SMALLINT NOT NULL,
    UserAgentMinor VARCHAR(255) NULL,
    CookieEnable SMALLINT NOT NULL,
    JavascriptEnable SMALLINT NOT NULL,
    IsMobile SMALLINT NOT NULL,
    MobilePhone SMALLINT NOT NULL,
    MobilePhoneModel VARCHAR(MAX) NULL,
    Params VARCHAR(MAX) NULL,
    IPNetworkID INT NOT NULL,
    TraficSourceID SMALLINT NOT NULL,
    SearchEngineID SMALLINT NOT NULL,
    SearchPhrase VARCHAR(MAX) NULL,
    AdvEngineID SMALLINT NOT NULL,
    IsArtifical SMALLINT NOT NULL,
    WindowClientWidth SMALLINT NOT NULL,
    WindowClientHeight SMALLINT NOT NULL,
    ClientTimeZone SMALLINT NOT NULL,
    ClientEventTime DATETIME2 NOT NULL,
    SilverlightVersion1 SMALLINT NOT NULL,
    SilverlightVersion2 SMALLINT NOT NULL,
    SilverlightVersion3 INT NOT NULL,
    SilverlightVersion4 SMALLINT NOT NULL,
    PageCharset VARCHAR(MAX) NULL,
    CodeVersion INT NOT NULL,
    IsLink SMALLINT NOT NULL,
    IsDownload SMALLINT NOT NULL,
    IsNotBounce SMALLINT NOT NULL,
    FUniqID BIGINT NOT NULL,
    OriginalURL VARCHAR(MAX) NULL,
    HID INT NOT NULL,
    IsOldCounter SMALLINT NOT NULL,
    IsEvent SMALLINT NOT NULL,
    IsParameter SMALLINT NOT NULL,
    DontCountHits SMALLINT NOT NULL,
    WithHash SMALLINT NOT NULL,
    HitColor CHAR(1) NULL,
    LocalEventTime DATETIME2 NOT NULL,
    Age SMALLINT NOT NULL,
    Sex SMALLINT NOT NULL,
    Income SMALLINT NOT NULL,
    Interests SMALLINT NOT NULL,
    Robotness SMALLINT NOT NULL,
    RemoteIP INT NOT NULL,
    WindowName INT NOT NULL,
    OpenerName INT NOT NULL,
    HistoryLength SMALLINT NOT NULL,
    BrowserLanguage VARCHAR(MAX) NULL,
    BrowserCountry VARCHAR(MAX) NULL,
    SocialNetwork VARCHAR(MAX) NULL,
    SocialAction VARCHAR(MAX) NULL,
    HTTPError SMALLINT NOT NULL,
    SendTiming INT NOT NULL,
    DNSTiming INT NOT NULL,
    ConnectTiming INT NOT NULL,
    ResponseStartTiming INT NOT NULL,
    ResponseEndTiming INT NOT NULL,
    FetchTiming INT NOT NULL,
    SocialSourceNetworkID SMALLINT NOT NULL,
    SocialSourcePage VARCHAR(MAX) NULL,
    ParamPrice BIGINT NOT NULL,
    ParamOrderID VARCHAR(MAX) NULL,
    ParamCurrency VARCHAR(MAX) NULL,
    ParamCurrencyID SMALLINT NOT NULL,
    OpenstatServiceName VARCHAR(MAX) NULL,
    OpenstatCampaignID VARCHAR(MAX) NULL,
    OpenstatAdID VARCHAR(MAX) NULL,
    OpenstatSourceID VARCHAR(MAX) NULL,
    UTMSource VARCHAR(MAX) NULL,
    UTMMedium VARCHAR(MAX) NULL,
    UTMCampaign VARCHAR(MAX) NULL,
    UTMContent VARCHAR(MAX) NULL,
    UTMTerm VARCHAR(MAX) NULL,
    FromTag VARCHAR(MAX) NULL,
    HasGCLID SMALLINT NOT NULL,
    RefererHash BIGINT NOT NULL,
    URLHash BIGINT NOT NULL,
    CLID INT NOT NULL
);
