#!/bin/bash
set -eu

PGVERSION=${PGVERSION:-17}

# Source: https://wiki.postgresql.org/wiki/Apt
sudo apt-get update -y
sudo apt-get install -y postgresql-common
sudo /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh -y

sudo apt-get update -y
sudo apt-get install -y postgresql-$PGVERSION

memory=$(awk '/MemTotal/ {print $2}' /proc/meminfo)
threads=$(nproc)
cpus=$(($threads / 2))
shared_buffers=$(($memory / 4))
effective_cache_size=$(($memory - ($memory / 4)))
max_worker_processes=$(($threads + 15))

sudo tee /etc/postgresql/$PGVERSION/main/conf.d/clickbench.conf <<EOF
shared_buffers=${shared_buffers}kB
max_worker_processes=${max_worker_processes}
max_parallel_workers=${threads}
max_parallel_maintenance_workers=${cpus}
max_parallel_workers_per_gather=${cpus}
max_wal_size=32GB
work_mem=64MB
effective_cache_size = ${effective_cache_size}kB
EOF

sudo systemctl restart postgresql@$PGVERSION-main
