#!/bin/bash
set -e

docker compose exec -T server clickhouse-client --port 52145 \
    --enable_multiple_tables_for_cnch_parts=1 \
    --query "SELECT sum(bytes_on_disk) FROM system.cnch_parts WHERE table = 'hits' AND database = 'bench'"
