CREATE OR REPLACE TABLE hits
(
    WatchID BIGINT NOT NULL CODEC(Iguana),
    JavaEnable SMALLINT NOT NULL CODEC(Iguana),
    Title TEXT NOT NULL CODEC(Iguana),
    GoodEvent SMALLINT NOT NULL CODEC(Iguana),
    EventTime TIMESTAMP NOT NULL CODEC(Iguana),
    EventDate Date NOT NULL CODEC(Iguana),
    CounterID INTEGER NOT NULL CODEC(Iguana),
    ClientIP INTEGER NOT NULL CODEC(Iguana),
    RegionID INTEGER NOT NULL CODEC(Iguana),
    UserID BIGINT NOT NULL CODEC(Iguana),
    CounterClass SMALLINT NOT NULL CODEC(Iguana),
    OS SMALLINT NOT NULL CODEC(Iguana),
    UserAgent SMALLINT NOT NULL CODEC(Iguana),
    URL TEXT NOT NULL CODEC(Iguana),
    Referer TEXT NOT NULL CODEC(Iguana),
    IsRefresh SMALLINT NOT NULL CODEC(Iguana),
    RefererCategoryID SMALLINT NOT NULL CODEC(Iguana),
    RefererRegionID INTEGER NOT NULL CODEC(Iguana),
    URLCategoryID SMALLINT NOT NULL CODEC(Iguana),
    URLRegionID INTEGER NOT NULL CODEC(Iguana),
    ResolutionWidth SMALLINT NOT NULL CODEC(Iguana),
    ResolutionHeight SMALLINT NOT NULL CODEC(Iguana),
    ResolutionDepth SMALLINT NOT NULL CODEC(Iguana),
    FlashMajor SMALLINT NOT NULL CODEC(Iguana),
    FlashMinor SMALLINT NOT NULL CODEC(Iguana),
    FlashMinor2 TEXT NOT NULL CODEC(Iguana),
    NetMajor SMALLINT NOT NULL CODEC(Iguana),
    NetMinor SMALLINT NOT NULL CODEC(Iguana),
    UserAgentMajor SMALLINT NOT NULL CODEC(Iguana),
    UserAgentMinor VARCHAR(255) NOT NULL CODEC(Iguana),
    CookieEnable SMALLINT NOT NULL CODEC(Iguana),
    JavascriptEnable SMALLINT NOT NULL CODEC(Iguana),
    IsMobile SMALLINT NOT NULL CODEC(Iguana),
    MobilePhone SMALLINT NOT NULL CODEC(Iguana),
    MobilePhoneModel TEXT NOT NULL CODEC(Iguana),
    Params TEXT NOT NULL CODEC(Iguana),
    IPNetworkID INTEGER NOT NULL CODEC(Iguana),
    TraficSourceID SMALLINT NOT NULL CODEC(Iguana),
    SearchEngineID SMALLINT NOT NULL CODEC(Iguana),
    SearchPhrase TEXT NOT NULL CODEC(Iguana),
    AdvEngineID SMALLINT NOT NULL CODEC(Iguana),
    IsArtifical SMALLINT NOT NULL CODEC(Iguana),
    WindowClientWidth SMALLINT NOT NULL CODEC(Iguana),
    WindowClientHeight SMALLINT NOT NULL CODEC(Iguana),
    ClientTimeZone SMALLINT NOT NULL CODEC(Iguana),
    ClientEventTime TIMESTAMP NOT NULL CODEC(Iguana),
    SilverlightVersion1 SMALLINT NOT NULL CODEC(Iguana),
    SilverlightVersion2 SMALLINT NOT NULL CODEC(Iguana),
    SilverlightVersion3 INTEGER NOT NULL CODEC(Iguana),
    SilverlightVersion4 SMALLINT NOT NULL CODEC(Iguana),
    PageCharset TEXT NOT NULL CODEC(Iguana),
    CodeVersion INTEGER NOT NULL CODEC(Iguana),
    IsLink SMALLINT NOT NULL CODEC(Iguana),
    IsDownload SMALLINT NOT NULL CODEC(Iguana),
    IsNotBounce SMALLINT NOT NULL CODEC(Iguana),
    FUniqID BIGINT NOT NULL CODEC(Iguana),
    OriginalURL TEXT NOT NULL CODEC(Iguana),
    HID INTEGER NOT NULL CODEC(Iguana),
    IsOldCounter SMALLINT NOT NULL CODEC(Iguana),
    IsEvent SMALLINT NOT NULL CODEC(Iguana),
    IsParameter SMALLINT NOT NULL CODEC(Iguana),
    DontCountHits SMALLINT NOT NULL CODEC(Iguana),
    WithHash SMALLINT NOT NULL CODEC(Iguana),
    HitColor CHAR NOT NULL CODEC(Iguana),
    LocalEventTime TIMESTAMP NOT NULL CODEC(Iguana),
    Age SMALLINT NOT NULL CODEC(Iguana),
    Sex SMALLINT NOT NULL CODEC(Iguana),
    Income SMALLINT NOT NULL CODEC(Iguana),
    Interests SMALLINT NOT NULL CODEC(Iguana),
    Robotness SMALLINT NOT NULL CODEC(Iguana),
    RemoteIP INTEGER NOT NULL CODEC(Iguana),
    WindowName INTEGER NOT NULL CODEC(Iguana),
    OpenerName INTEGER NOT NULL CODEC(Iguana),
    HistoryLength SMALLINT NOT NULL CODEC(Iguana),
    BrowserLanguage TEXT NOT NULL CODEC(Iguana),
    BrowserCountry TEXT NOT NULL CODEC(Iguana),
    SocialNetwork TEXT NOT NULL CODEC(Iguana),
    SocialAction TEXT NOT NULL CODEC(Iguana),
    HTTPError SMALLINT NOT NULL CODEC(Iguana),
    SendTiming INTEGER NOT NULL CODEC(Iguana),
    DNSTiming INTEGER NOT NULL CODEC(Iguana),
    ConnectTiming INTEGER NOT NULL CODEC(Iguana),
    ResponseStartTiming INTEGER NOT NULL CODEC(Iguana),
    ResponseEndTiming INTEGER NOT NULL CODEC(Iguana),
    FetchTiming INTEGER NOT NULL CODEC(Iguana),
    SocialSourceNetworkID SMALLINT NOT NULL CODEC(Iguana),
    SocialSourcePage TEXT NOT NULL CODEC(Iguana),
    ParamPrice BIGINT NOT NULL CODEC(Iguana),
    ParamOrderID TEXT NOT NULL CODEC(Iguana),
    ParamCurrency TEXT NOT NULL CODEC(Iguana),
    ParamCurrencyID SMALLINT NOT NULL CODEC(Iguana),
    OpenstatServiceName TEXT NOT NULL CODEC(Iguana),
    OpenstatCampaignID TEXT NOT NULL CODEC(Iguana),
    OpenstatAdID TEXT NOT NULL CODEC(Iguana),
    OpenstatSourceID TEXT NOT NULL CODEC(Iguana),
    UTMSource TEXT NOT NULL CODEC(Iguana),
    UTMMedium TEXT NOT NULL CODEC(Iguana),
    UTMCampaign TEXT NOT NULL CODEC(Iguana),
    UTMContent TEXT NOT NULL CODEC(Iguana),
    UTMTerm TEXT NOT NULL CODEC(Iguana),
    FromTag TEXT NOT NULL CODEC(Iguana),
    HasGCLID SMALLINT NOT NULL CODEC(Iguana),
    RefererHash BIGINT NOT NULL CODEC(Iguana),
    URLHash BIGINT NOT NULL CODEC(Iguana),
    CLID INTEGER NOT NULL CODEC(Iguana),
    PRIMARY KEY (CounterID, EventDate, UserID, EventTime, WatchID)
)
ENGINE = MergeTree
-- The point of this run: every column is compressed with the experimental
-- `Iguana` codec (https://github.com/ClickHouse/ClickHouse/pull/107560) instead
-- of the size-aware LZ4/ZSTD(3) default that the stock `clickhouse` run gets.
--
-- Spelled out per column rather than as `SETTINGS default_compression_codec =
-- 'Iguana'`: that setting is a codec *name string*, and the string path
-- (`CompressionCodecFactory::get(const String &)`) upper-cases the name before
-- looking it up in a case-sensitive family map, so any mixed-case codec name
-- fails with `Unknown codec family: IGUANA` (`Quantized` fails the same way;
-- `ZSTD`/`LZ4`/`ALP` happen to be spelled in upper case and so work). The
-- `<compression>` server-config `<method>` path has the same limitation.
-- Since no column here carries a codec of its own, per-column `CODEC(Iguana)`
-- is equivalent to the table default: it applies to the initial INSERT and to
-- every background merge, and leaves `marks_compression_codec` and
-- `primary_key_compression_codec` at their defaults, so only column data moves.
--
-- Requires `enable_iguana_codec = 1`, set in the default profile by ./install.
SETTINGS fsync_after_insert = 1, -- https://github.com/ClickHouse/ClickBench/issues/678
    auto_statistics_types = ''; -- per-column uniqState blobs grow with cardinality (~140 KB for high-card columns × ~30 such columns ≈ 4 MB per part of statistics.packed). Cold queries pay the load cost before cached_estimator is populated by the bg refresh task. Disabling stops the auto-stats files from being created on merge.
