#!/usr/bin/env bash
# Prepare the TPC-DS dataset as oldest-ClickHouse-compatible Native files.
#
# TPC-DS is produced by the standard `dsdgen` data generator at scale
# TPCDS_SCALE (default 32, ~10 GB compressed); GEN points at a generator that
# understands `INSTALL tpcds; CALL dsdgen(sf=N)` SQL. The schema (24 tables) is
# taken from the ClickHouse repository (tests/benchmarks/tpc-ds/init.sql); the
# only type the earliest
# ClickHouse cannot handle is Decimal, which is downgraded to Float64. Every
# table also gets a constant synth_date so the legacy positional MergeTree
# engine works (see create/create.sh); NULLs (TPC-DS has many optional foreign
# keys) are replaced with type defaults so the non-Nullable columns load.
# Column order and names match create/schema/<table>.columns exactly.

set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CLICKHOUSE="${CLICKHOUSE:-$HOME/clickhouse}"
GEN="${GEN:-generator}"
SCALE="${TPCDS_SCALE:-32}"
WORK="${HERE}/data/tpcds-work"
mkdir -p "${WORK}"

command -v "${CLICKHOUSE}" >/dev/null 2>&1 || CLICKHOUSE=clickhouse
[ -x "${GEN}" ] || command -v "${GEN}" >/dev/null 2>&1 || {
    echo "generator '${GEN}' not found; set GEN to a data generator" >&2; exit 1; }

echo "tpcds: generating scale factor ${SCALE}"
rm -f "${WORK}/tpcds.db"
"${GEN}" "${WORK}/tpcds.db" <<SQL
INSTALL tpcds; LOAD tpcds;
CALL dsdgen(sf=${SCALE});
SQL

TABLES="call_center catalog_page catalog_returns catalog_sales customer_address customer_demographics customer date_dim household_demographics income_band inventory item promotion reason ship_mode store_returns store_sales store time_dim warehouse web_page web_returns web_sales web_site"
for t in ${TABLES}; do
    "${GEN}" "${WORK}/tpcds.db" \
        "COPY (SELECT * FROM ${t}) TO '${WORK}/${t}.parquet' (FORMAT parquet);"
done

# Re-emit each parquet table as oldest-compatible Native, columns in the order
# of create/schema/<table>.columns (Decimal -> Float64, NULL -> type default).
conv() {
    local t="$1" sel="$2"
    "${CLICKHOUSE}" local --max_memory_usage 0 \
        --query "SELECT ${sel} FROM file('${WORK}/${t}.parquet','Parquet') FORMAT Native" \
        | zstd -q -6 -T0 -c > "${HERE}/data/tpcds_${t}.native.zst"
    echo "  tpcds_${t}.native.zst: $(du -h "${HERE}/data/tpcds_${t}.native.zst" | cut -f1)"
}

conv call_center "CAST('2000-01-01' AS Date) AS synth_date, CAST(ifNull(cc_call_center_sk, 0) AS Int64) AS cc_call_center_sk, CAST(ifNull(cc_call_center_id, '') AS FixedString(16)) AS cc_call_center_id, CAST(ifNull(cc_rec_start_date, toDate(0)) AS Date) AS cc_rec_start_date, CAST(ifNull(cc_rec_end_date, toDate(0)) AS Date) AS cc_rec_end_date, CAST(ifNull(cc_closed_date_sk, 0) AS UInt32) AS cc_closed_date_sk, CAST(ifNull(cc_open_date_sk, 0) AS UInt32) AS cc_open_date_sk, CAST(ifNull(cc_name, '') AS String) AS cc_name, CAST(ifNull(cc_class, '') AS String) AS cc_class, CAST(ifNull(cc_employees, 0) AS Int64) AS cc_employees, CAST(ifNull(cc_sq_ft, 0) AS Int64) AS cc_sq_ft, CAST(ifNull(cc_hours, '') AS FixedString(20)) AS cc_hours, CAST(ifNull(cc_manager, '') AS String) AS cc_manager, CAST(ifNull(cc_mkt_id, 0) AS Int64) AS cc_mkt_id, CAST(ifNull(cc_mkt_class, '') AS FixedString(50)) AS cc_mkt_class, CAST(ifNull(cc_mkt_desc, '') AS String) AS cc_mkt_desc, CAST(ifNull(cc_market_manager, '') AS String) AS cc_market_manager, CAST(ifNull(cc_division, 0) AS Int64) AS cc_division, CAST(ifNull(cc_division_name, '') AS String) AS cc_division_name, CAST(ifNull(cc_company, 0) AS Int64) AS cc_company, CAST(ifNull(cc_company_name, '') AS FixedString(50)) AS cc_company_name, CAST(ifNull(cc_street_number, '') AS FixedString(10)) AS cc_street_number, CAST(ifNull(cc_street_name, '') AS String) AS cc_street_name, CAST(ifNull(cc_street_type, '') AS FixedString(15)) AS cc_street_type, CAST(ifNull(cc_suite_number, '') AS FixedString(10)) AS cc_suite_number, CAST(ifNull(cc_city, '') AS String) AS cc_city, CAST(ifNull(cc_county, '') AS String) AS cc_county, CAST(ifNull(cc_state, '') AS FixedString(2)) AS cc_state, CAST(ifNull(cc_zip, '') AS FixedString(10)) AS cc_zip, CAST(ifNull(cc_country, '') AS String) AS cc_country, CAST(ifNull(cc_gmt_offset, 0) AS Float64) AS cc_gmt_offset, CAST(ifNull(cc_tax_percentage, 0) AS Float64) AS cc_tax_percentage"
conv catalog_page "CAST('2000-01-01' AS Date) AS synth_date, CAST(ifNull(cp_catalog_page_sk, 0) AS Int64) AS cp_catalog_page_sk, CAST(ifNull(cp_catalog_page_id, '') AS FixedString(16)) AS cp_catalog_page_id, CAST(ifNull(cp_start_date_sk, 0) AS UInt32) AS cp_start_date_sk, CAST(ifNull(cp_end_date_sk, 0) AS UInt32) AS cp_end_date_sk, CAST(ifNull(cp_department, '') AS String) AS cp_department, CAST(ifNull(cp_catalog_number, 0) AS Int64) AS cp_catalog_number, CAST(ifNull(cp_catalog_page_number, 0) AS Int64) AS cp_catalog_page_number, CAST(ifNull(cp_description, '') AS String) AS cp_description, CAST(ifNull(cp_type, '') AS String) AS cp_type"
conv catalog_returns "CAST('2000-01-01' AS Date) AS synth_date, CAST(ifNull(cr_returned_date_sk, 0) AS UInt32) AS cr_returned_date_sk, CAST(ifNull(cr_returned_time_sk, 0) AS UInt32) AS cr_returned_time_sk, CAST(ifNull(cr_item_sk, 0) AS Int64) AS cr_item_sk, CAST(ifNull(cr_refunded_customer_sk, 0) AS Int64) AS cr_refunded_customer_sk, CAST(ifNull(cr_refunded_cdemo_sk, 0) AS Int64) AS cr_refunded_cdemo_sk, CAST(ifNull(cr_refunded_hdemo_sk, 0) AS Int64) AS cr_refunded_hdemo_sk, CAST(ifNull(cr_refunded_addr_sk, 0) AS Int64) AS cr_refunded_addr_sk, CAST(ifNull(cr_returning_customer_sk, 0) AS Int64) AS cr_returning_customer_sk, CAST(ifNull(cr_returning_cdemo_sk, 0) AS Int64) AS cr_returning_cdemo_sk, CAST(ifNull(cr_returning_hdemo_sk, 0) AS Int64) AS cr_returning_hdemo_sk, CAST(ifNull(cr_returning_addr_sk, 0) AS Int64) AS cr_returning_addr_sk, CAST(ifNull(cr_call_center_sk, 0) AS Int64) AS cr_call_center_sk, CAST(ifNull(cr_catalog_page_sk, 0) AS Int64) AS cr_catalog_page_sk, CAST(ifNull(cr_ship_mode_sk, 0) AS Int64) AS cr_ship_mode_sk, CAST(ifNull(cr_warehouse_sk, 0) AS Int64) AS cr_warehouse_sk, CAST(ifNull(cr_reason_sk, 0) AS Int64) AS cr_reason_sk, CAST(ifNull(cr_order_number, 0) AS Int64) AS cr_order_number, CAST(ifNull(cr_return_quantity, 0) AS Int64) AS cr_return_quantity, CAST(ifNull(cr_return_amount, 0) AS Float64) AS cr_return_amount, CAST(ifNull(cr_return_tax, 0) AS Float64) AS cr_return_tax, CAST(ifNull(cr_return_amt_inc_tax, 0) AS Float64) AS cr_return_amt_inc_tax, CAST(ifNull(cr_fee, 0) AS Float64) AS cr_fee, CAST(ifNull(cr_return_ship_cost, 0) AS Float64) AS cr_return_ship_cost, CAST(ifNull(cr_refunded_cash, 0) AS Float64) AS cr_refunded_cash, CAST(ifNull(cr_reversed_charge, 0) AS Float64) AS cr_reversed_charge, CAST(ifNull(cr_store_credit, 0) AS Float64) AS cr_store_credit, CAST(ifNull(cr_net_loss, 0) AS Float64) AS cr_net_loss"
conv catalog_sales "CAST('2000-01-01' AS Date) AS synth_date, CAST(ifNull(cs_sold_date_sk, 0) AS UInt32) AS cs_sold_date_sk, CAST(ifNull(cs_sold_time_sk, 0) AS UInt32) AS cs_sold_time_sk, CAST(ifNull(cs_ship_date_sk, 0) AS UInt32) AS cs_ship_date_sk, CAST(ifNull(cs_bill_customer_sk, 0) AS Int64) AS cs_bill_customer_sk, CAST(ifNull(cs_bill_cdemo_sk, 0) AS Int64) AS cs_bill_cdemo_sk, CAST(ifNull(cs_bill_hdemo_sk, 0) AS Int64) AS cs_bill_hdemo_sk, CAST(ifNull(cs_bill_addr_sk, 0) AS Int64) AS cs_bill_addr_sk, CAST(ifNull(cs_ship_customer_sk, 0) AS Int64) AS cs_ship_customer_sk, CAST(ifNull(cs_ship_cdemo_sk, 0) AS Int64) AS cs_ship_cdemo_sk, CAST(ifNull(cs_ship_hdemo_sk, 0) AS Int64) AS cs_ship_hdemo_sk, CAST(ifNull(cs_ship_addr_sk, 0) AS Int64) AS cs_ship_addr_sk, CAST(ifNull(cs_call_center_sk, 0) AS Int64) AS cs_call_center_sk, CAST(ifNull(cs_catalog_page_sk, 0) AS Int64) AS cs_catalog_page_sk, CAST(ifNull(cs_ship_mode_sk, 0) AS Int64) AS cs_ship_mode_sk, CAST(ifNull(cs_warehouse_sk, 0) AS Int64) AS cs_warehouse_sk, CAST(ifNull(cs_item_sk, 0) AS Int64) AS cs_item_sk, CAST(ifNull(cs_promo_sk, 0) AS Int64) AS cs_promo_sk, CAST(ifNull(cs_order_number, 0) AS Int64) AS cs_order_number, CAST(ifNull(cs_quantity, 0) AS Int64) AS cs_quantity, CAST(ifNull(cs_wholesale_cost, 0) AS Float64) AS cs_wholesale_cost, CAST(ifNull(cs_list_price, 0) AS Float64) AS cs_list_price, CAST(ifNull(cs_sales_price, 0) AS Float64) AS cs_sales_price, CAST(ifNull(cs_ext_discount_amt, 0) AS Float64) AS cs_ext_discount_amt, CAST(ifNull(cs_ext_sales_price, 0) AS Float64) AS cs_ext_sales_price, CAST(ifNull(cs_ext_wholesale_cost, 0) AS Float64) AS cs_ext_wholesale_cost, CAST(ifNull(cs_ext_list_price, 0) AS Float64) AS cs_ext_list_price, CAST(ifNull(cs_ext_tax, 0) AS Float64) AS cs_ext_tax, CAST(ifNull(cs_coupon_amt, 0) AS Float64) AS cs_coupon_amt, CAST(ifNull(cs_ext_ship_cost, 0) AS Float64) AS cs_ext_ship_cost, CAST(ifNull(cs_net_paid, 0) AS Float64) AS cs_net_paid, CAST(ifNull(cs_net_paid_inc_tax, 0) AS Float64) AS cs_net_paid_inc_tax, CAST(ifNull(cs_net_paid_inc_ship, 0) AS Float64) AS cs_net_paid_inc_ship, CAST(ifNull(cs_net_paid_inc_ship_tax, 0) AS Float64) AS cs_net_paid_inc_ship_tax, CAST(ifNull(cs_net_profit, 0) AS Float64) AS cs_net_profit"
conv customer_address "CAST('2000-01-01' AS Date) AS synth_date, CAST(ifNull(ca_address_sk, 0) AS Int64) AS ca_address_sk, CAST(ifNull(ca_address_id, '') AS FixedString(16)) AS ca_address_id, CAST(ifNull(ca_street_number, '') AS FixedString(10)) AS ca_street_number, CAST(ifNull(ca_street_name, '') AS String) AS ca_street_name, CAST(ifNull(ca_street_type, '') AS FixedString(15)) AS ca_street_type, CAST(ifNull(ca_suite_number, '') AS FixedString(10)) AS ca_suite_number, CAST(ifNull(ca_city, '') AS String) AS ca_city, CAST(ifNull(ca_county, '') AS String) AS ca_county, CAST(ifNull(ca_state, '') AS FixedString(2)) AS ca_state, CAST(ifNull(ca_zip, '') AS FixedString(10)) AS ca_zip, CAST(ifNull(ca_country, '') AS String) AS ca_country, CAST(ifNull(ca_gmt_offset, 0) AS Float64) AS ca_gmt_offset, CAST(ifNull(ca_location_type, '') AS FixedString(20)) AS ca_location_type"
conv customer_demographics "CAST('2000-01-01' AS Date) AS synth_date, CAST(ifNull(cd_demo_sk, 0) AS Int64) AS cd_demo_sk, CAST(ifNull(cd_gender, '') AS FixedString(1)) AS cd_gender, CAST(ifNull(cd_marital_status, '') AS FixedString(1)) AS cd_marital_status, CAST(ifNull(cd_education_status, '') AS FixedString(20)) AS cd_education_status, CAST(ifNull(cd_purchase_estimate, 0) AS Int64) AS cd_purchase_estimate, CAST(ifNull(cd_credit_rating, '') AS FixedString(10)) AS cd_credit_rating, CAST(ifNull(cd_dep_count, 0) AS Int64) AS cd_dep_count, CAST(ifNull(cd_dep_employed_count, 0) AS Int64) AS cd_dep_employed_count, CAST(ifNull(cd_dep_college_count, 0) AS Int64) AS cd_dep_college_count"
conv customer "CAST('2000-01-01' AS Date) AS synth_date, CAST(ifNull(c_customer_sk, 0) AS Int64) AS c_customer_sk, CAST(ifNull(c_customer_id, '') AS FixedString(16)) AS c_customer_id, CAST(ifNull(c_current_cdemo_sk, 0) AS Int64) AS c_current_cdemo_sk, CAST(ifNull(c_current_hdemo_sk, 0) AS Int64) AS c_current_hdemo_sk, CAST(ifNull(c_current_addr_sk, 0) AS Int64) AS c_current_addr_sk, CAST(ifNull(c_first_shipto_date_sk, 0) AS UInt32) AS c_first_shipto_date_sk, CAST(ifNull(c_first_sales_date_sk, 0) AS UInt32) AS c_first_sales_date_sk, CAST(ifNull(c_salutation, '') AS FixedString(10)) AS c_salutation, CAST(ifNull(c_first_name, '') AS FixedString(20)) AS c_first_name, CAST(ifNull(c_last_name, '') AS FixedString(30)) AS c_last_name, CAST(ifNull(c_preferred_cust_flag, '') AS FixedString(1)) AS c_preferred_cust_flag, CAST(ifNull(c_birth_day, 0) AS Int64) AS c_birth_day, CAST(ifNull(c_birth_month, 0) AS Int64) AS c_birth_month, CAST(ifNull(c_birth_year, 0) AS Int64) AS c_birth_year, CAST(ifNull(c_birth_country, '') AS String) AS c_birth_country, CAST(ifNull(c_login, '') AS FixedString(13)) AS c_login, CAST(ifNull(c_email_address, '') AS FixedString(50)) AS c_email_address, CAST(ifNull(c_last_review_date_sk, 0) AS UInt32) AS c_last_review_date_sk"
conv date_dim "CAST('2000-01-01' AS Date) AS synth_date, CAST(ifNull(d_date_sk, 0) AS UInt32) AS d_date_sk, CAST(ifNull(d_date_id, '') AS FixedString(16)) AS d_date_id, CAST(ifNull(d_date, toDate(0)) AS Date) AS d_date, CAST(ifNull(d_month_seq, 0) AS Int64) AS d_month_seq, CAST(ifNull(d_week_seq, 0) AS Int64) AS d_week_seq, CAST(ifNull(d_quarter_seq, 0) AS Int64) AS d_quarter_seq, CAST(ifNull(d_year, 0) AS Int64) AS d_year, CAST(ifNull(d_dow, 0) AS Int64) AS d_dow, CAST(ifNull(d_moy, 0) AS Int64) AS d_moy, CAST(ifNull(d_dom, 0) AS Int64) AS d_dom, CAST(ifNull(d_qoy, 0) AS Int64) AS d_qoy, CAST(ifNull(d_fy_year, 0) AS Int64) AS d_fy_year, CAST(ifNull(d_fy_quarter_seq, 0) AS Int64) AS d_fy_quarter_seq, CAST(ifNull(d_fy_week_seq, 0) AS Int64) AS d_fy_week_seq, CAST(ifNull(d_day_name, '') AS FixedString(9)) AS d_day_name, CAST(ifNull(d_quarter_name, '') AS FixedString(6)) AS d_quarter_name, CAST(ifNull(d_holiday, '') AS FixedString(1)) AS d_holiday, CAST(ifNull(d_weekend, '') AS FixedString(1)) AS d_weekend, CAST(ifNull(d_following_holiday, '') AS FixedString(1)) AS d_following_holiday, CAST(ifNull(d_first_dom, 0) AS Int64) AS d_first_dom, CAST(ifNull(d_last_dom, 0) AS Int64) AS d_last_dom, CAST(ifNull(d_same_day_ly, 0) AS Int64) AS d_same_day_ly, CAST(ifNull(d_same_day_lq, 0) AS Int64) AS d_same_day_lq, CAST(ifNull(d_current_day, '') AS FixedString(1)) AS d_current_day, CAST(ifNull(d_current_week, '') AS FixedString(1)) AS d_current_week, CAST(ifNull(d_current_month, '') AS FixedString(1)) AS d_current_month, CAST(ifNull(d_current_quarter, '') AS FixedString(1)) AS d_current_quarter, CAST(ifNull(d_current_year, '') AS FixedString(1)) AS d_current_year"
conv household_demographics "CAST('2000-01-01' AS Date) AS synth_date, CAST(ifNull(hd_demo_sk, 0) AS Int64) AS hd_demo_sk, CAST(ifNull(hd_income_band_sk, 0) AS Int64) AS hd_income_band_sk, CAST(ifNull(hd_buy_potential, '') AS FixedString(15)) AS hd_buy_potential, CAST(ifNull(hd_dep_count, 0) AS Int64) AS hd_dep_count, CAST(ifNull(hd_vehicle_count, 0) AS Int64) AS hd_vehicle_count"
conv income_band "CAST('2000-01-01' AS Date) AS synth_date, CAST(ifNull(ib_income_band_sk, 0) AS Int64) AS ib_income_band_sk, CAST(ifNull(ib_lower_bound, 0) AS Int64) AS ib_lower_bound, CAST(ifNull(ib_upper_bound, 0) AS Int64) AS ib_upper_bound"
conv inventory "CAST('2000-01-01' AS Date) AS synth_date, CAST(ifNull(inv_date_sk, 0) AS UInt32) AS inv_date_sk, CAST(ifNull(inv_item_sk, 0) AS Int64) AS inv_item_sk, CAST(ifNull(inv_warehouse_sk, 0) AS Int64) AS inv_warehouse_sk, CAST(ifNull(inv_quantity_on_hand, 0) AS Int64) AS inv_quantity_on_hand"
conv item "CAST('2000-01-01' AS Date) AS synth_date, CAST(ifNull(i_item_sk, 0) AS Int64) AS i_item_sk, CAST(ifNull(i_item_id, '') AS FixedString(16)) AS i_item_id, CAST(ifNull(i_rec_start_date, toDate(0)) AS Date) AS i_rec_start_date, CAST(ifNull(i_rec_end_date, toDate(0)) AS Date) AS i_rec_end_date, CAST(ifNull(i_item_desc, '') AS String) AS i_item_desc, CAST(ifNull(i_current_price, 0) AS Float64) AS i_current_price, CAST(ifNull(i_wholesale_cost, 0) AS Float64) AS i_wholesale_cost, CAST(ifNull(i_brand_id, 0) AS Int64) AS i_brand_id, CAST(ifNull(i_brand, '') AS FixedString(50)) AS i_brand, CAST(ifNull(i_class_id, 0) AS Int64) AS i_class_id, CAST(ifNull(i_class, '') AS FixedString(50)) AS i_class, CAST(ifNull(i_category_id, 0) AS Int64) AS i_category_id, CAST(ifNull(i_category, '') AS FixedString(50)) AS i_category, CAST(ifNull(i_manufact_id, 0) AS Int64) AS i_manufact_id, CAST(ifNull(i_manufact, '') AS FixedString(50)) AS i_manufact, CAST(ifNull(i_size, '') AS FixedString(20)) AS i_size, CAST(ifNull(i_formulation, '') AS FixedString(20)) AS i_formulation, CAST(ifNull(i_color, '') AS FixedString(20)) AS i_color, CAST(ifNull(i_units, '') AS FixedString(10)) AS i_units, CAST(ifNull(i_container, '') AS FixedString(10)) AS i_container, CAST(ifNull(i_manager_id, 0) AS Int64) AS i_manager_id, CAST(ifNull(i_product_name, '') AS FixedString(50)) AS i_product_name"
conv promotion "CAST('2000-01-01' AS Date) AS synth_date, CAST(ifNull(p_promo_sk, 0) AS Int64) AS p_promo_sk, CAST(ifNull(p_promo_id, '') AS FixedString(16)) AS p_promo_id, CAST(ifNull(p_start_date_sk, 0) AS UInt32) AS p_start_date_sk, CAST(ifNull(p_end_date_sk, 0) AS UInt32) AS p_end_date_sk, CAST(ifNull(p_item_sk, 0) AS Int64) AS p_item_sk, CAST(ifNull(p_cost, 0) AS Float64) AS p_cost, CAST(ifNull(p_response_target, 0) AS Int64) AS p_response_target, CAST(ifNull(p_promo_name, '') AS FixedString(50)) AS p_promo_name, CAST(ifNull(p_channel_dmail, '') AS FixedString(1)) AS p_channel_dmail, CAST(ifNull(p_channel_email, '') AS FixedString(1)) AS p_channel_email, CAST(ifNull(p_channel_catalog, '') AS FixedString(1)) AS p_channel_catalog, CAST(ifNull(p_channel_tv, '') AS FixedString(1)) AS p_channel_tv, CAST(ifNull(p_channel_radio, '') AS FixedString(1)) AS p_channel_radio, CAST(ifNull(p_channel_press, '') AS FixedString(1)) AS p_channel_press, CAST(ifNull(p_channel_event, '') AS FixedString(1)) AS p_channel_event, CAST(ifNull(p_channel_demo, '') AS FixedString(1)) AS p_channel_demo, CAST(ifNull(p_channel_details, '') AS String) AS p_channel_details, CAST(ifNull(p_purpose, '') AS FixedString(15)) AS p_purpose, CAST(ifNull(p_discount_active, '') AS FixedString(1)) AS p_discount_active"
conv reason "CAST('2000-01-01' AS Date) AS synth_date, CAST(ifNull(r_reason_sk, 0) AS Int64) AS r_reason_sk, CAST(ifNull(r_reason_id, '') AS FixedString(16)) AS r_reason_id, CAST(ifNull(r_reason_desc, '') AS FixedString(100)) AS r_reason_desc"
conv ship_mode "CAST('2000-01-01' AS Date) AS synth_date, CAST(ifNull(sm_ship_mode_sk, 0) AS Int64) AS sm_ship_mode_sk, CAST(ifNull(sm_ship_mode_id, '') AS FixedString(16)) AS sm_ship_mode_id, CAST(ifNull(sm_type, '') AS FixedString(30)) AS sm_type, CAST(ifNull(sm_code, '') AS FixedString(10)) AS sm_code, CAST(ifNull(sm_carrier, '') AS FixedString(20)) AS sm_carrier, CAST(ifNull(sm_contract, '') AS FixedString(20)) AS sm_contract"
conv store_returns "CAST('2000-01-01' AS Date) AS synth_date, CAST(ifNull(sr_returned_date_sk, 0) AS UInt32) AS sr_returned_date_sk, CAST(ifNull(sr_return_time_sk, 0) AS UInt32) AS sr_return_time_sk, CAST(ifNull(sr_item_sk, 0) AS Int64) AS sr_item_sk, CAST(ifNull(sr_customer_sk, 0) AS Int64) AS sr_customer_sk, CAST(ifNull(sr_cdemo_sk, 0) AS Int64) AS sr_cdemo_sk, CAST(ifNull(sr_hdemo_sk, 0) AS Int64) AS sr_hdemo_sk, CAST(ifNull(sr_addr_sk, 0) AS Int64) AS sr_addr_sk, CAST(ifNull(sr_store_sk, 0) AS Int64) AS sr_store_sk, CAST(ifNull(sr_reason_sk, 0) AS Int64) AS sr_reason_sk, CAST(ifNull(sr_ticket_number, 0) AS Int64) AS sr_ticket_number, CAST(ifNull(sr_return_quantity, 0) AS Int64) AS sr_return_quantity, CAST(ifNull(sr_return_amt, 0) AS Float64) AS sr_return_amt, CAST(ifNull(sr_return_tax, 0) AS Float64) AS sr_return_tax, CAST(ifNull(sr_return_amt_inc_tax, 0) AS Float64) AS sr_return_amt_inc_tax, CAST(ifNull(sr_fee, 0) AS Float64) AS sr_fee, CAST(ifNull(sr_return_ship_cost, 0) AS Float64) AS sr_return_ship_cost, CAST(ifNull(sr_refunded_cash, 0) AS Float64) AS sr_refunded_cash, CAST(ifNull(sr_reversed_charge, 0) AS Float64) AS sr_reversed_charge, CAST(ifNull(sr_store_credit, 0) AS Float64) AS sr_store_credit, CAST(ifNull(sr_net_loss, 0) AS Float64) AS sr_net_loss"
conv store_sales "CAST('2000-01-01' AS Date) AS synth_date, CAST(ifNull(ss_sold_date_sk, 0) AS UInt32) AS ss_sold_date_sk, CAST(ifNull(ss_sold_time_sk, 0) AS UInt32) AS ss_sold_time_sk, CAST(ifNull(ss_item_sk, 0) AS Int64) AS ss_item_sk, CAST(ifNull(ss_customer_sk, 0) AS Int64) AS ss_customer_sk, CAST(ifNull(ss_cdemo_sk, 0) AS Int64) AS ss_cdemo_sk, CAST(ifNull(ss_hdemo_sk, 0) AS Int64) AS ss_hdemo_sk, CAST(ifNull(ss_addr_sk, 0) AS Int64) AS ss_addr_sk, CAST(ifNull(ss_store_sk, 0) AS Int64) AS ss_store_sk, CAST(ifNull(ss_promo_sk, 0) AS Int64) AS ss_promo_sk, CAST(ifNull(ss_ticket_number, 0) AS Int64) AS ss_ticket_number, CAST(ifNull(ss_quantity, 0) AS Int64) AS ss_quantity, CAST(ifNull(ss_wholesale_cost, 0) AS Float64) AS ss_wholesale_cost, CAST(ifNull(ss_list_price, 0) AS Float64) AS ss_list_price, CAST(ifNull(ss_sales_price, 0) AS Float64) AS ss_sales_price, CAST(ifNull(ss_ext_discount_amt, 0) AS Float64) AS ss_ext_discount_amt, CAST(ifNull(ss_ext_sales_price, 0) AS Float64) AS ss_ext_sales_price, CAST(ifNull(ss_ext_wholesale_cost, 0) AS Float64) AS ss_ext_wholesale_cost, CAST(ifNull(ss_ext_list_price, 0) AS Float64) AS ss_ext_list_price, CAST(ifNull(ss_ext_tax, 0) AS Float64) AS ss_ext_tax, CAST(ifNull(ss_coupon_amt, 0) AS Float64) AS ss_coupon_amt, CAST(ifNull(ss_net_paid, 0) AS Float64) AS ss_net_paid, CAST(ifNull(ss_net_paid_inc_tax, 0) AS Float64) AS ss_net_paid_inc_tax, CAST(ifNull(ss_net_profit, 0) AS Float64) AS ss_net_profit"
conv store "CAST('2000-01-01' AS Date) AS synth_date, CAST(ifNull(s_store_sk, 0) AS Int64) AS s_store_sk, CAST(ifNull(s_store_id, '') AS FixedString(16)) AS s_store_id, CAST(ifNull(s_rec_start_date, toDate(0)) AS Date) AS s_rec_start_date, CAST(ifNull(s_rec_end_date, toDate(0)) AS Date) AS s_rec_end_date, CAST(ifNull(s_closed_date_sk, 0) AS UInt32) AS s_closed_date_sk, CAST(ifNull(s_store_name, '') AS String) AS s_store_name, CAST(ifNull(s_number_employees, 0) AS Int64) AS s_number_employees, CAST(ifNull(s_floor_space, 0) AS Int64) AS s_floor_space, CAST(ifNull(s_hours, '') AS FixedString(20)) AS s_hours, CAST(ifNull(s_manager, '') AS String) AS s_manager, CAST(ifNull(s_market_id, 0) AS Int64) AS s_market_id, CAST(ifNull(s_geography_class, '') AS String) AS s_geography_class, CAST(ifNull(s_market_desc, '') AS String) AS s_market_desc, CAST(ifNull(s_market_manager, '') AS String) AS s_market_manager, CAST(ifNull(s_division_id, 0) AS Int64) AS s_division_id, CAST(ifNull(s_division_name, '') AS String) AS s_division_name, CAST(ifNull(s_company_id, 0) AS Int64) AS s_company_id, CAST(ifNull(s_company_name, '') AS String) AS s_company_name, CAST(ifNull(s_street_number, '') AS String) AS s_street_number, CAST(ifNull(s_street_name, '') AS String) AS s_street_name, CAST(ifNull(s_street_type, '') AS FixedString(15)) AS s_street_type, CAST(ifNull(s_suite_number, '') AS FixedString(10)) AS s_suite_number, CAST(ifNull(s_city, '') AS String) AS s_city, CAST(ifNull(s_county, '') AS String) AS s_county, CAST(ifNull(s_state, '') AS FixedString(2)) AS s_state, CAST(ifNull(s_zip, '') AS FixedString(10)) AS s_zip, CAST(ifNull(s_country, '') AS String) AS s_country, CAST(ifNull(s_gmt_offset, 0) AS Float64) AS s_gmt_offset, CAST(ifNull(s_tax_percentage, 0) AS Float64) AS s_tax_percentage"
conv time_dim "CAST('2000-01-01' AS Date) AS synth_date, CAST(ifNull(t_time_sk, 0) AS UInt32) AS t_time_sk, CAST(ifNull(t_time_id, '') AS FixedString(16)) AS t_time_id, CAST(ifNull(t_time, 0) AS Int64) AS t_time, CAST(ifNull(t_hour, 0) AS Int64) AS t_hour, CAST(ifNull(t_minute, 0) AS Int64) AS t_minute, CAST(ifNull(t_second, 0) AS Int64) AS t_second, CAST(ifNull(t_am_pm, '') AS FixedString(2)) AS t_am_pm, CAST(ifNull(t_shift, '') AS FixedString(20)) AS t_shift, CAST(ifNull(t_sub_shift, '') AS FixedString(20)) AS t_sub_shift, CAST(ifNull(t_meal_time, '') AS FixedString(20)) AS t_meal_time"
conv warehouse "CAST('2000-01-01' AS Date) AS synth_date, CAST(ifNull(w_warehouse_sk, 0) AS Int64) AS w_warehouse_sk, CAST(ifNull(w_warehouse_id, '') AS FixedString(16)) AS w_warehouse_id, CAST(ifNull(w_warehouse_name, '') AS String) AS w_warehouse_name, CAST(ifNull(w_warehouse_sq_ft, 0) AS Int64) AS w_warehouse_sq_ft, CAST(ifNull(w_street_number, '') AS FixedString(10)) AS w_street_number, CAST(ifNull(w_street_name, '') AS String) AS w_street_name, CAST(ifNull(w_street_type, '') AS FixedString(15)) AS w_street_type, CAST(ifNull(w_suite_number, '') AS FixedString(10)) AS w_suite_number, CAST(ifNull(w_city, '') AS String) AS w_city, CAST(ifNull(w_county, '') AS String) AS w_county, CAST(ifNull(w_state, '') AS FixedString(2)) AS w_state, CAST(ifNull(w_zip, '') AS FixedString(10)) AS w_zip, CAST(ifNull(w_country, '') AS String) AS w_country, CAST(ifNull(w_gmt_offset, 0) AS Float64) AS w_gmt_offset"
conv web_page "CAST('2000-01-01' AS Date) AS synth_date, CAST(ifNull(wp_web_page_sk, 0) AS Int64) AS wp_web_page_sk, CAST(ifNull(wp_web_page_id, '') AS FixedString(16)) AS wp_web_page_id, CAST(ifNull(wp_rec_start_date, toDate(0)) AS Date) AS wp_rec_start_date, CAST(ifNull(wp_rec_end_date, toDate(0)) AS Date) AS wp_rec_end_date, CAST(ifNull(wp_creation_date_sk, 0) AS UInt32) AS wp_creation_date_sk, CAST(ifNull(wp_access_date_sk, 0) AS UInt32) AS wp_access_date_sk, CAST(ifNull(wp_autogen_flag, '') AS FixedString(1)) AS wp_autogen_flag, CAST(ifNull(wp_customer_sk, 0) AS Int64) AS wp_customer_sk, CAST(ifNull(wp_url, '') AS String) AS wp_url, CAST(ifNull(wp_type, '') AS FixedString(50)) AS wp_type, CAST(ifNull(wp_char_count, 0) AS Int64) AS wp_char_count, CAST(ifNull(wp_link_count, 0) AS Int64) AS wp_link_count, CAST(ifNull(wp_image_count, 0) AS Int64) AS wp_image_count, CAST(ifNull(wp_max_ad_count, 0) AS Int64) AS wp_max_ad_count"
conv web_returns "CAST('2000-01-01' AS Date) AS synth_date, CAST(ifNull(wr_returned_date_sk, 0) AS UInt32) AS wr_returned_date_sk, CAST(ifNull(wr_returned_time_sk, 0) AS UInt32) AS wr_returned_time_sk, CAST(ifNull(wr_item_sk, 0) AS Int64) AS wr_item_sk, CAST(ifNull(wr_refunded_customer_sk, 0) AS Int64) AS wr_refunded_customer_sk, CAST(ifNull(wr_refunded_cdemo_sk, 0) AS Int64) AS wr_refunded_cdemo_sk, CAST(ifNull(wr_refunded_hdemo_sk, 0) AS Int64) AS wr_refunded_hdemo_sk, CAST(ifNull(wr_refunded_addr_sk, 0) AS Int64) AS wr_refunded_addr_sk, CAST(ifNull(wr_returning_customer_sk, 0) AS Int64) AS wr_returning_customer_sk, CAST(ifNull(wr_returning_cdemo_sk, 0) AS Int64) AS wr_returning_cdemo_sk, CAST(ifNull(wr_returning_hdemo_sk, 0) AS Int64) AS wr_returning_hdemo_sk, CAST(ifNull(wr_returning_addr_sk, 0) AS Int64) AS wr_returning_addr_sk, CAST(ifNull(wr_web_page_sk, 0) AS Int64) AS wr_web_page_sk, CAST(ifNull(wr_reason_sk, 0) AS Int64) AS wr_reason_sk, CAST(ifNull(wr_order_number, 0) AS Int64) AS wr_order_number, CAST(ifNull(wr_return_quantity, 0) AS Int64) AS wr_return_quantity, CAST(ifNull(wr_return_amt, 0) AS Float64) AS wr_return_amt, CAST(ifNull(wr_return_tax, 0) AS Float64) AS wr_return_tax, CAST(ifNull(wr_return_amt_inc_tax, 0) AS Float64) AS wr_return_amt_inc_tax, CAST(ifNull(wr_fee, 0) AS Float64) AS wr_fee, CAST(ifNull(wr_return_ship_cost, 0) AS Float64) AS wr_return_ship_cost, CAST(ifNull(wr_refunded_cash, 0) AS Float64) AS wr_refunded_cash, CAST(ifNull(wr_reversed_charge, 0) AS Float64) AS wr_reversed_charge, CAST(ifNull(wr_account_credit, 0) AS Float64) AS wr_account_credit, CAST(ifNull(wr_net_loss, 0) AS Float64) AS wr_net_loss"
conv web_sales "CAST('2000-01-01' AS Date) AS synth_date, CAST(ifNull(ws_sold_date_sk, 0) AS UInt32) AS ws_sold_date_sk, CAST(ifNull(ws_sold_time_sk, 0) AS UInt32) AS ws_sold_time_sk, CAST(ifNull(ws_ship_date_sk, 0) AS UInt32) AS ws_ship_date_sk, CAST(ifNull(ws_item_sk, 0) AS Int64) AS ws_item_sk, CAST(ifNull(ws_bill_customer_sk, 0) AS Int64) AS ws_bill_customer_sk, CAST(ifNull(ws_bill_cdemo_sk, 0) AS Int64) AS ws_bill_cdemo_sk, CAST(ifNull(ws_bill_hdemo_sk, 0) AS Int64) AS ws_bill_hdemo_sk, CAST(ifNull(ws_bill_addr_sk, 0) AS Int64) AS ws_bill_addr_sk, CAST(ifNull(ws_ship_customer_sk, 0) AS Int64) AS ws_ship_customer_sk, CAST(ifNull(ws_ship_cdemo_sk, 0) AS Int64) AS ws_ship_cdemo_sk, CAST(ifNull(ws_ship_hdemo_sk, 0) AS Int64) AS ws_ship_hdemo_sk, CAST(ifNull(ws_ship_addr_sk, 0) AS Int64) AS ws_ship_addr_sk, CAST(ifNull(ws_web_page_sk, 0) AS Int64) AS ws_web_page_sk, CAST(ifNull(ws_web_site_sk, 0) AS Int64) AS ws_web_site_sk, CAST(ifNull(ws_ship_mode_sk, 0) AS Int64) AS ws_ship_mode_sk, CAST(ifNull(ws_warehouse_sk, 0) AS Int64) AS ws_warehouse_sk, CAST(ifNull(ws_promo_sk, 0) AS Int64) AS ws_promo_sk, CAST(ifNull(ws_order_number, 0) AS Int64) AS ws_order_number, CAST(ifNull(ws_quantity, 0) AS Int64) AS ws_quantity, CAST(ifNull(ws_wholesale_cost, 0) AS Float64) AS ws_wholesale_cost, CAST(ifNull(ws_list_price, 0) AS Float64) AS ws_list_price, CAST(ifNull(ws_sales_price, 0) AS Float64) AS ws_sales_price, CAST(ifNull(ws_ext_discount_amt, 0) AS Float64) AS ws_ext_discount_amt, CAST(ifNull(ws_ext_sales_price, 0) AS Float64) AS ws_ext_sales_price, CAST(ifNull(ws_ext_wholesale_cost, 0) AS Float64) AS ws_ext_wholesale_cost, CAST(ifNull(ws_ext_list_price, 0) AS Float64) AS ws_ext_list_price, CAST(ifNull(ws_ext_tax, 0) AS Float64) AS ws_ext_tax, CAST(ifNull(ws_coupon_amt, 0) AS Float64) AS ws_coupon_amt, CAST(ifNull(ws_ext_ship_cost, 0) AS Float64) AS ws_ext_ship_cost, CAST(ifNull(ws_net_paid, 0) AS Float64) AS ws_net_paid, CAST(ifNull(ws_net_paid_inc_tax, 0) AS Float64) AS ws_net_paid_inc_tax, CAST(ifNull(ws_net_paid_inc_ship, 0) AS Float64) AS ws_net_paid_inc_ship, CAST(ifNull(ws_net_paid_inc_ship_tax, 0) AS Float64) AS ws_net_paid_inc_ship_tax, CAST(ifNull(ws_net_profit, 0) AS Float64) AS ws_net_profit"
conv web_site "CAST('2000-01-01' AS Date) AS synth_date, CAST(ifNull(web_site_sk, 0) AS Int64) AS web_site_sk, CAST(ifNull(web_site_id, '') AS FixedString(16)) AS web_site_id, CAST(ifNull(web_rec_start_date, toDate(0)) AS Date) AS web_rec_start_date, CAST(ifNull(web_rec_end_date, toDate(0)) AS Date) AS web_rec_end_date, CAST(ifNull(web_name, '') AS String) AS web_name, CAST(ifNull(web_open_date_sk, 0) AS UInt32) AS web_open_date_sk, CAST(ifNull(web_close_date_sk, 0) AS UInt32) AS web_close_date_sk, CAST(ifNull(web_class, '') AS String) AS web_class, CAST(ifNull(web_manager, '') AS String) AS web_manager, CAST(ifNull(web_mkt_id, 0) AS Int64) AS web_mkt_id, CAST(ifNull(web_mkt_class, '') AS String) AS web_mkt_class, CAST(ifNull(web_mkt_desc, '') AS String) AS web_mkt_desc, CAST(ifNull(web_market_manager, '') AS String) AS web_market_manager, CAST(ifNull(web_company_id, 0) AS Int64) AS web_company_id, CAST(ifNull(web_company_name, '') AS FixedString(50)) AS web_company_name, CAST(ifNull(web_street_number, '') AS FixedString(10)) AS web_street_number, CAST(ifNull(web_street_name, '') AS String) AS web_street_name, CAST(ifNull(web_street_type, '') AS FixedString(15)) AS web_street_type, CAST(ifNull(web_suite_number, '') AS FixedString(10)) AS web_suite_number, CAST(ifNull(web_city, '') AS String) AS web_city, CAST(ifNull(web_county, '') AS String) AS web_county, CAST(ifNull(web_state, '') AS FixedString(2)) AS web_state, CAST(ifNull(web_zip, '') AS FixedString(10)) AS web_zip, CAST(ifNull(web_country, '') AS String) AS web_country, CAST(ifNull(web_gmt_offset, 0) AS Float64) AS web_gmt_offset, CAST(ifNull(web_tax_percentage, 0) AS Float64) AS web_tax_percentage"
rm -rf "${WORK}"
echo "tpcds: done"
