#!/bin/bash
set -e

source benchmark_variables.sh
START_DIR=$(pwd)
export YDB_PASSWORD=password

cert_dir=$(find "$START_DIR/ydb-ansible-examples/TLS/CA/certs" -maxdepth 1 -type d -not -path "." -printf "%T@ %p\n" \
    | sort -n | tail -n 1 | cut -d' ' -f2-)

echo "$YDB_PASSWORD" | "$START_DIR/ydb-ansible-examples/3-nodes-mirror-3-dc/files/ydb" \
    -e "grpcs://$host1$host_suffix:2135" -d /Root/database \
    --ca-file "$cert_dir/ca.crt" --user root yql -s 'SELECT 1' >/dev/null 2>&1
