#!/bin/bash
set -eu

sudo apt-get update -y
sudo apt-get install -y mysql-server-8.0

sudo bash -c "echo -e '[mysql]\nlocal-infile=1\n\n[mysqld]\nlocal-infile=1\n' > /etc/mysql/conf.d/local_infile.cnf"
sudo service mysql restart
