#!/bin/bash
set -e

if [ ! -x ./octosql ]; then
    wget --continue --progress=dot:giga \
        https://github.com/cube2222/octosql/releases/download/v0.13.0/octosql_0.13.0_linux_amd64.tar.gz
    tar xf octosql_0.13.0_linux_amd64.tar.gz octosql
fi
