jd 'reads count jdindex from hits'
jd 'reads count jdindex from hits where AdvEngineID <> 0'
jd 'reads sum AdvEngineID,count jdindex,avg ResolutionWidth from hits'
jd 'reads avg UserID from hits'
# ~. ; }. jd 'reads UserID from hits'
# ~. ; }. jd 'reads SearchPhrase from hits'
jd 'reads min EventDate,max EventDate from hits'
10 {. jd 'reads c:count jdindex by AdvEngineID from hits where AdvEngineID <> 0 order by c desc'
10 {. jd 'reads u:count jdindex by RegionID from hits order by u desc'
10 {. jd 'reads sum AdvEngineID,c:count jdindex,avg ResolutionWidth,d:count jdindex by RegionID from hits order by c desc'
10 {. jd 'reads u:count jdindex by MobilePhoneModel from hits where MobilePhoneModel <> "" order by u desc'
10 {. jd 'reads u:count jdindex by MobilePhone,MobilePhoneModel from hits where MobilePhoneModel <> "" order by u desc'
10 {. jd 'reads c:count jdindex by SearchPhrase from hits where SearchPhrase <> "" order by c desc'
10 {. jd 'reads u:count jdindex by SearchPhrase from hits where SearchPhrase <> "" order by u desc'
10 {. jd 'reads c:count jdindex by SearchEngineID,SearchPhrase from hits where SearchPhrase <> "" order by c desc'
10 {. jd 'reads c:count jdindex by UserID from hits order by c desc'
10 {. jd 'reads c:count jdindex by UserID,SearchPhrase from hits order by c desc'
10 {. jd 'reads c:count jdindex by UserID,SearchPhrase from hits'
10 {. jd 'reads c:count jdindex by UserID,SearchPhrase from hits order by c desc'
jd 'reads UserID from hits where UserID = 435090932899640449'
jd 'reads count jdindex from hits where URL like ".*google.*"'
10 {. jd 'reads first URL,c:count jdindex by SearchPhrase from hits where URL like ".*google.*" && SearchPhrase <> "" order by c desc'
10 {. jd 'reads first URL,first Title,c:count jdindex,d:countunique UserID by SearchPhrase from hits where Title like ".*Google.*" && URL unlike ".*\.google\..*" && SearchPhrase <> "" order by c desc'
10 {. jd 'reads * from hits where URL like ".*google.*" order by EventTime'
10 {. jd 'reads EventTime,SearchPhrase from hits where SearchPhrase <> "" order by EventTime'
10 {. jd 'reads SearchPhrase from hits where SearchPhrase <> "" order by SearchPhrase'
10 {. jd 'reads EventTime,SearchPhrase from hits where SearchPhrase <> "" order by EventTime,SearchPhrase'
'null'
'null'
jd 'reads sum ResolutionWidth from hits'
10 {. jd 'reads c:count jdindex,sum IsRefresh,avg ResolutionWidth by SearchEngineID,ClientIP from hits where SearchPhrase <> "" order by c desc'
10 {. jd 'reads c:count jdindex,sum IsRefresh,avg ResolutionWidth by WatchID,ClientIP from hits where SearchPhrase <> "" order by c desc'
10 {. jd 'reads c:count jdindex,sum IsRefresh,avg ResolutionWidth by WatchID,ClientIP from hits order by c desc'
10 {. jd 'reads c:count jdindex by URL from hits order by c desc'
10 {. jd 'reads c:count jdindex by URL from hits order by c desc'
10 {. jd 'reads c:count jdindex by ClientIP from hits order by c desc'
10 {. jd 'reads c:count jdindex by URL from hits where CounterID=62 && EventDate range ("2013-07-01","2013-07-31") && DontCountHits=0 && IsRefresh=0 && URL <> "" order by c desc'
10 {. jd 'reads c:count jdindex by Title from hits where CounterID=62 && EventDate range ("2013-07-01","2013-07-31") && DontCountHits=0 && IsRefresh=0 && Title <> "" order by c desc'
10 {. (1000 }. jd 'reads c:count jdindex by URL from hits where CounterID=62 && EventDate range ("2013-07-01","2013-07-31") && IsRefresh=0 && IsLink<>0 && IsDownload=0 order by c desc')
10 {. (1000 }. jd 'reads c:count jdindex by TraficSourceID,SearchEngineID,AdvEngineID,Referer,URL from hits where CounterID=62 && EventDate range ("2013-07-01","2013-07-31") && IsRefresh=0 order by c desc')
10 {. (100 }. jd 'reads c:count jdindex by URLHash,EventDate from hits where CounterID=62 && EventDate range ("2013-07-01","2013-07-31") && IsRefresh=0 && TraficSourceID in (-1,6) && RefererHash=3594120000172545465 order by c desc')
10 {. (10000 }. jd 'reads c:count jdindex by WindowClientWidth,WindowClientHeight from hits where CounterID=62 && EventDate range ("2013-07-01","2013-07-31") && IsRefresh=0 && DontCountHits=0 && URLHash=2868770270353813622 order by c desc')
'null'
