-- Schema is inferred by CTAS in `./load`:
--   CREATE TABLE hits AS SELECT * FROM 'hits.parquet';
--
-- slothdb's parser doesn't accept DuckDB's `SELECT * REPLACE (...)`
-- rewrite, so the typed CREATE TABLE used by ClickBench in general
-- (BIGINT WatchID, TEXT URL, TIMESTAMP EventTime, ...) is not loaded
-- explicitly; the column types come from the parquet file's own
-- logical types. EventDate / *Time stay as integers rather than
-- becoming DATE / TIMESTAMP.
