#!/bin/bash
set -eu

sudo apt-get update -y
sudo apt-get install -y git golang pigz python3 python3-pip jq bc

if [ ! -d siglens ]; then
    git clone https://github.com/siglens/siglens.git --branch 1.0.54
fi

cd siglens
go mod tidy
if [ ! -x ./siglens ]; then
    go build -o siglens cmd/siglens/main.go
fi

# load script uses requests.
pip3 install --quiet --break-system-packages requests || pip3 install --quiet requests
