#!/bin/bash
set -e

# shellcheck disable=SC1091
source /opt/greenplum-db-*/greenplum_path.sh
export MASTER_DATA_DIRECTORY=${MASTER_DATA_DIRECTORY:-/gpmaster/gpsne-1/}
psql -d postgres -t -c 'SELECT 1' >/dev/null
