#!/bin/bash

# shellcheck disable=SC1091
source /opt/greenplum-db-*/greenplum_path.sh 2>/dev/null || true
export MASTER_DATA_DIRECTORY=${MASTER_DATA_DIRECTORY:-/gpmaster/gpsne-1/}
gpstop -a 2>/dev/null || true
