#!/bin/bash
set -e

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
: "${ZIGHOUSE_DATA_DIR:=${SCRIPT_DIR}/zighouse-store}"

du -sb "$ZIGHOUSE_DATA_DIR" 2>/dev/null | awk '{ print $1 }' \
    || du -sk "$ZIGHOUSE_DATA_DIR" | awk '{ print $1 * 1024 }'
