CREATE DATABASE IF NOT EXISTS clickbench;
USE clickbench;

DROP VIEW IF EXISTS hits;
DROP TABLE IF EXISTS hits_raw;

CREATE EXTERNAL TABLE hits_raw (
    WatchID bigint,
    JavaEnable smallint,
    Title string,
    GoodEvent smallint,
    EventTime bigint,
    EventDate int,
    CounterID int,
    ClientIP int,
    RegionID int,
    UserID bigint,
    CounterClass smallint,
    OS smallint,
    UserAgent smallint,
    URL string,
    Referer string,
    IsRefresh smallint,
    RefererCategoryID smallint,
    RefererRegionID int,
    URLCategoryID smallint,
    URLRegionID int,
    ResolutionWidth smallint,
    ResolutionHeight smallint,
    ResolutionDepth smallint,
    FlashMajor smallint,
    FlashMinor smallint,
    FlashMinor2 string,
    NetMajor smallint,
    NetMinor smallint,
    UserAgentMajor smallint,
    UserAgentMinor string,
    CookieEnable smallint,
    JavascriptEnable smallint,
    IsMobile smallint,
    MobilePhone smallint,
    MobilePhoneModel string,
    Params string,
    IPNetworkID int,
    TraficSourceID smallint,
    SearchEngineID smallint,
    SearchPhrase string,
    AdvEngineID smallint,
    IsArtifical smallint,
    WindowClientWidth smallint,
    WindowClientHeight smallint,
    ClientTimeZone smallint,
    ClientEventTime bigint,
    SilverlightVersion1 smallint,
    SilverlightVersion2 smallint,
    SilverlightVersion3 int,
    SilverlightVersion4 smallint,
    PageCharset string,
    CodeVersion int,
    IsLink smallint,
    IsDownload smallint,
    IsNotBounce smallint,
    FUniqID bigint,
    OriginalURL string,
    HID int,
    IsOldCounter smallint,
    IsEvent smallint,
    IsParameter smallint,
    DontCountHits smallint,
    WithHash smallint,
    HitColor string,
    LocalEventTime bigint,
    Age smallint,
    Sex smallint,
    Income smallint,
    Interests smallint,
    Robotness smallint,
    RemoteIP int,
    WindowName int,
    OpenerName int,
    HistoryLength smallint,
    BrowserLanguage string,
    BrowserCountry string,
    SocialNetwork string,
    SocialAction string,
    HTTPError smallint,
    SendTiming int,
    DNSTiming int,
    ConnectTiming int,
    ResponseStartTiming int,
    ResponseEndTiming int,
    FetchTiming int,
    SocialSourceNetworkID smallint,
    SocialSourcePage string,
    ParamPrice bigint,
    ParamOrderID string,
    ParamCurrency string,
    ParamCurrencyID smallint,
    OpenstatServiceName string,
    OpenstatCampaignID string,
    OpenstatAdID string,
    OpenstatSourceID string,
    UTMSource string,
    UTMMedium string,
    UTMCampaign string,
    UTMContent string,
    UTMTerm string,
    FromTag string,
    HasGCLID smallint,
    RefererHash bigint,
    URLHash bigint,
    CLID int
)
STORED AS PARQUET
LOCATION 'file:///clickbench/hits';

-- The Parquet file stores EventTime/ClientEventTime/LocalEventTime as Unix epoch seconds (BIGINT)
-- and EventDate as days since 1970-01-01 (INT). Wrap the raw table in a view that exposes the
-- standard ClickBench types so the queries below need no further adaptation. CAST() of
-- from_unixtime() turns Hive's "yyyy-MM-dd HH:mm:ss" string into a TIMESTAMP, and
-- date_add(DATE'1970-01-01', n) yields a DATE.
CREATE VIEW hits AS
SELECT
    WatchID, JavaEnable, Title, GoodEvent,
    CAST(from_unixtime(EventTime) AS TIMESTAMP) AS EventTime,
    date_add(DATE '1970-01-01', EventDate) AS EventDate,
    CounterID, ClientIP, RegionID, UserID, CounterClass, OS, UserAgent,
    URL, Referer, IsRefresh, RefererCategoryID, RefererRegionID,
    URLCategoryID, URLRegionID, ResolutionWidth, ResolutionHeight,
    ResolutionDepth, FlashMajor, FlashMinor, FlashMinor2, NetMajor, NetMinor,
    UserAgentMajor, UserAgentMinor, CookieEnable, JavascriptEnable,
    IsMobile, MobilePhone, MobilePhoneModel, Params, IPNetworkID,
    TraficSourceID, SearchEngineID, SearchPhrase, AdvEngineID, IsArtifical,
    WindowClientWidth, WindowClientHeight, ClientTimeZone,
    CAST(from_unixtime(ClientEventTime) AS TIMESTAMP) AS ClientEventTime,
    SilverlightVersion1, SilverlightVersion2, SilverlightVersion3,
    SilverlightVersion4, PageCharset, CodeVersion, IsLink, IsDownload,
    IsNotBounce, FUniqID, OriginalURL, HID, IsOldCounter, IsEvent,
    IsParameter, DontCountHits, WithHash, HitColor,
    CAST(from_unixtime(LocalEventTime) AS TIMESTAMP) AS LocalEventTime,
    Age, Sex, Income, Interests, Robotness, RemoteIP, WindowName,
    OpenerName, HistoryLength, BrowserLanguage, BrowserCountry,
    SocialNetwork, SocialAction, HTTPError, SendTiming, DNSTiming,
    ConnectTiming, ResponseStartTiming, ResponseEndTiming, FetchTiming,
    SocialSourceNetworkID, SocialSourcePage, ParamPrice, ParamOrderID,
    ParamCurrency, ParamCurrencyID, OpenstatServiceName, OpenstatCampaignID,
    OpenstatAdID, OpenstatSourceID, UTMSource, UTMMedium, UTMCampaign,
    UTMContent, UTMTerm, FromTag, HasGCLID, RefererHash, URLHash, CLID
FROM hits_raw;
