CREATE TABLE "ki_home"."hits"
(
    "WatchID" BIGINT NOT NULL,
    "JavaEnable" TINYINT NOT NULL,
    "Title" VARCHAR NOT NULL,
    "GoodEvent" TINYINT NOT NULL,
    "EventTime" DATETIME NOT NULL,
    "EventDate" DATE (dict) NOT NULL,
    "CounterID" INTEGER (dict) NOT NULL,
    "ClientIP" INTEGER NOT NULL,
    "RegionID" INTEGER (dict) NOT NULL,
    "UserID" BIGINT NOT NULL,
    "CounterClass" SMALLINT NOT NULL,
    "OS" SMALLINT NOT NULL,
    "UserAgent" SMALLINT NOT NULL,
    "URL" VARCHAR NOT NULL,
    "Referer" VARCHAR NOT NULL,
    "Refresh" TINYINT NOT NULL,
    "RefererCategoryID" SMALLINT NOT NULL,
    "RefererRegionID" INTEGER (dict) NOT NULL,
    "URLCategoryID" SMALLINT NOT NULL,
    "URLRegionID" INTEGER (dict) NOT NULL,
    "ResolutionWidth" SMALLINT NOT NULL,
    "ResolutionHeight" SMALLINT NOT NULL,
    "ResolutionDepth" SMALLINT NOT NULL,
    "FlashMajor" SMALLINT NOT NULL,
    "FlashMinor" SMALLINT NOT NULL,
    "FlashMinor2" VARCHAR (16, dict) NOT NULL,
    "NetMajor" SMALLINT NOT NULL,
    "NetMinor" SMALLINT NOT NULL,
    "UserAgentMajor" SMALLINT NOT NULL,
    "UserAgentMinor" VARCHAR (4, dict) NOT NULL,
    "CookieEnable" TINYINT NOT NULL,
    "JavascriptEnable" TINYINT NOT NULL,
    "IsMobile" TINYINT NOT NULL,
    "MobilePhone" SMALLINT NOT NULL,
    "MobilePhoneModel" VARCHAR (32, dict) NOT NULL,
    "Params" VARCHAR (dict) NOT NULL,
    "IPNetworkID" INTEGER NOT NULL,
    "TraficSourceID" SMALLINT NOT NULL,
    "SearchEngineID" SMALLINT NOT NULL,
    "SearchPhrase" VARCHAR NOT NULL,
    "AdvEngineID" SMALLINT NOT NULL,
    "IsArtifical" TINYINT NOT NULL,
    "WindowClientWidth" SMALLINT NOT NULL,
    "WindowClientHeight" SMALLINT NOT NULL,
    "ClientTimeZone" SMALLINT NOT NULL,
    "ClientEventTime" DATETIME NOT NULL,
    "SilverlightVersion1" SMALLINT NOT NULL,
    "SilverlightVersion2" SMALLINT NOT NULL,
    "SilverlightVersion3" INTEGER (dict) NOT NULL,
    "SilverlightVersion4" SMALLINT NOT NULL,
    "PageCharset" VARCHAR (64, dict) NOT NULL,
    "CodeVersion" INTEGER (dict) NOT NULL,
    "IsLink" TINYINT NOT NULL,
    "IsDownload" TINYINT NOT NULL,
    "IsNotBounce" TINYINT NOT NULL,
    "FUniqID" BIGINT NOT NULL,
    "OriginalURL" VARCHAR NOT NULL,
    "HID" INTEGER NOT NULL,
    "IsOldCounter" TINYINT NOT NULL,
    "IsEvent" TINYINT NOT NULL,
    "IsParameter" TINYINT NOT NULL,
    "DontCountHits" SMALLINT NOT NULL,
    "WithHash" SMALLINT NOT NULL,
    "HitColor" VARCHAR (1, dict) NOT NULL,
    "LocalEventTime" DATETIME NOT NULL,
    "Age" TINYINT NOT NULL,
    "Sex" TINYINT NOT NULL,
    "Income" SMALLINT NOT NULL,
    "Interests" SMALLINT NOT NULL,
    "Robotness" SMALLINT NOT NULL,
    "RemoteIP" INTEGER NOT NULL,
    "WindowName" INTEGER NOT NULL,
    "OpenerName" INTEGER (dict) NOT NULL,
    "HistoryLength" SMALLINT NOT NULL,
    "BrowserLanguage" VARCHAR (4, dict) NOT NULL,
    "BrowserCountry" VARCHAR (8, dict) NOT NULL,
    "SocialNetwork" VARCHAR (dict) NOT NULL,
    "SocialAction" VARCHAR (dict) NOT NULL,
    "HTTPError" SMALLINT NOT NULL,
    "SendTiming" INTEGER NOT NULL,
    "DNSTiming" INTEGER NOT NULL,
    "ConnectTiming" INTEGER NOT NULL,
    "ResponseStartTiming" INTEGER NOT NULL,
    "ResponseEndTiming" INTEGER NOT NULL,
    "FetchTiming" INTEGER NOT NULL,
    "SocialSourceNetworkID" SMALLINT NOT NULL,
    "SocialSourcePage" VARCHAR (128, dict) NOT NULL,
    "ParamPrice" BIGINT (dict) NOT NULL,
    "ParamOrderID" VARCHAR (16, dict) NOT NULL,
    "ParamCurrency" VARCHAR (8, dict) NOT NULL,
    "ParamCurrencyID" SMALLINT NOT NULL,
    "OpenstatServiceName" VARCHAR (16, dict) NOT NULL,
    "OpenstatCampaignID" VARCHAR (256, dict) NOT NULL,
    "OpenstatAdID" VARCHAR (64, dict) NOT NULL,
    "OpenstatSourceID" VARCHAR (64, dict) NOT NULL,
    "UTMSource" VARCHAR (32, dict) NOT NULL,
    "UTMMedium" VARCHAR (32, dict) NOT NULL,
    "UTMCampaign" VARCHAR (256, dict) NOT NULL,
    "UTMContent" VARCHAR (256, dict) NOT NULL,
    "UTMTerm" VARCHAR (256, dict) NOT NULL,
    "FromTag" VARCHAR (64, dict) NOT NULL,
    "HasGCLID" SMALLINT NOT NULL,
    "RefererHash" BIGINT NOT NULL,
    "URLHash" BIGINT NOT NULL,
    "CLID" INTEGER (dict) NOT NULL
)
TIER STRATEGY (
    ( ( VRAM 1, RAM 5, DISK0 5, PERSIST 5 ) )
);


