#!/bin/bash
set -eu

sudo chmod og+rX ~
chmod 777 hits.tsv

sudo -u postgres psql -t -c "DROP DATABASE IF EXISTS test"
sudo -u postgres psql -t -c "CREATE DATABASE test"
sudo -u postgres psql test -c "CREATE EXTENSION IF NOT EXISTS timescaledb;"

sudo -u postgres psql -v ON_ERROR_STOP=1 test < create.sql

sudo -u postgres psql -v ON_ERROR_STOP=1 test -c "SELECT create_hypertable('hits', 'eventtime', chunk_time_interval => interval '3 day', create_default_indexes => false)"
sudo -u postgres psql -v ON_ERROR_STOP=1 test -c "ALTER TABLE hits SET (timescaledb.compress, timescaledb.compress_segmentby = '', timescaledb.compress_orderby = 'counterid, userid, eventtime')"
sudo -u postgres psql -v ON_ERROR_STOP=1 test -c "ALTER DATABASE test SET timescaledb.enable_chunk_skipping to ON;"
sudo -u postgres psql -v ON_ERROR_STOP=1 -c "ALTER DATABASE test SET work_mem TO '1GB';"
sudo -u postgres psql -v ON_ERROR_STOP=1 -c "ALTER DATABASE test SET min_parallel_table_scan_size TO '0';"
sudo -u postgres psql -v ON_ERROR_STOP=1 test -c "SELECT enable_chunk_skipping('hits', 'counterid');"

sudo -u postgres psql -v ON_ERROR_STOP=1 test -t -c "\\copy hits FROM 'hits.tsv'"
sudo -u postgres psql -v ON_ERROR_STOP=1 test -q -c "SELECT compress_chunk(i, if_not_compressed => true) FROM show_chunks('hits') i"
sudo -u postgres psql -v ON_ERROR_STOP=1 test -q -t -c "vacuum freeze analyze hits;"

rm -f hits.tsv
sync
