USE clickbench;

DROP VIEW IF EXISTS hits_kudu;
DROP TABLE IF EXISTS hits_kudu_raw;

CREATE TABLE hits_kudu_raw (
    WatchID bigint,
    EventTime timestamp,
    JavaEnable smallint,
    Title string,
    GoodEvent smallint,
    EventDate date,
    CounterID int,
    ClientIP int,
    RegionID int,
    UserID bigint,
    CounterClass smallint,
    OS smallint,
    UserAgent smallint,
    URL string,
    Referer string,
    IsRefresh smallint,
    RefererCategoryID smallint,
    RefererRegionID int,
    URLCategoryID smallint,
    URLRegionID int,
    ResolutionWidth smallint,
    ResolutionHeight smallint,
    ResolutionDepth smallint,
    FlashMajor smallint,
    FlashMinor smallint,
    FlashMinor2 string,
    NetMajor smallint,
    NetMinor smallint,
    UserAgentMajor smallint,
    UserAgentMinor string,
    CookieEnable smallint,
    JavascriptEnable smallint,
    IsMobile smallint,
    MobilePhone smallint,
    MobilePhoneModel string,
    Params string,
    IPNetworkID int,
    TraficSourceID smallint,
    SearchEngineID smallint,
    SearchPhrase string,
    AdvEngineID smallint,
    IsArtifical smallint,
    WindowClientWidth smallint,
    WindowClientHeight smallint,
    ClientTimeZone smallint,
    ClientEventTime timestamp,
    SilverlightVersion1 smallint,
    SilverlightVersion2 smallint,
    SilverlightVersion3 int,
    SilverlightVersion4 smallint,
    PageCharset string,
    CodeVersion int,
    IsLink smallint,
    IsDownload smallint,
    IsNotBounce smallint,
    FUniqID bigint,
    OriginalURL string,
    HID int,
    IsOldCounter smallint,
    IsEvent smallint,
    IsParameter smallint,
    DontCountHits smallint,
    WithHash smallint,
    HitColor string,
    LocalEventTime timestamp,
    Age smallint,
    Sex smallint,
    Income smallint,
    Interests smallint,
    Robotness smallint,
    RemoteIP int,
    WindowName int,
    OpenerName int,
    HistoryLength smallint,
    BrowserLanguage string,
    BrowserCountry string,
    SocialNetwork string,
    SocialAction string,
    HTTPError smallint,
    SendTiming int,
    DNSTiming int,
    ConnectTiming int,
    ResponseStartTiming int,
    ResponseEndTiming int,
    FetchTiming int,
    SocialSourceNetworkID smallint,
    SocialSourcePage string,
    ParamPrice bigint,
    ParamOrderID string,
    ParamCurrency string,
    ParamCurrencyID smallint,
    OpenstatServiceName string,
    OpenstatCampaignID string,
    OpenstatAdID string,
    OpenstatSourceID string,
    UTMSource string,
    UTMMedium string,
    UTMCampaign string,
    UTMContent string,
    UTMTerm string,
    FromTag string,
    HasGCLID smallint,
    RefererHash bigint,
    URLHash bigint,
    CLID int,
    PRIMARY KEY (WatchID, EventTime)
)
PARTITION BY HASH (WatchID) PARTITIONS 2
STORED AS KUDU
TBLPROPERTIES (
    'kudu.master_addresses' = 'kudu-master:7051',
    'kudu.num_tablet_replicas' = '1'
);

-- Kudu requires primary-key columns to lead the physical schema. Expose a
-- projection in canonical ClickBench order so SELECT * remains comparable.
CREATE VIEW hits_kudu AS
SELECT
    WatchID, JavaEnable, Title, GoodEvent, EventTime, EventDate,
    CounterID, ClientIP, RegionID, UserID, CounterClass, OS,
    UserAgent, URL, Referer, IsRefresh, RefererCategoryID, RefererRegionID,
    URLCategoryID, URLRegionID, ResolutionWidth, ResolutionHeight, ResolutionDepth, FlashMajor,
    FlashMinor, FlashMinor2, NetMajor, NetMinor, UserAgentMajor, UserAgentMinor,
    CookieEnable, JavascriptEnable, IsMobile, MobilePhone, MobilePhoneModel, Params,
    IPNetworkID, TraficSourceID, SearchEngineID, SearchPhrase, AdvEngineID, IsArtifical,
    WindowClientWidth, WindowClientHeight, ClientTimeZone, ClientEventTime, SilverlightVersion1, SilverlightVersion2,
    SilverlightVersion3, SilverlightVersion4, PageCharset, CodeVersion, IsLink, IsDownload,
    IsNotBounce, FUniqID, OriginalURL, HID, IsOldCounter, IsEvent,
    IsParameter, DontCountHits, WithHash, HitColor, LocalEventTime, Age,
    Sex, Income, Interests, Robotness, RemoteIP, WindowName,
    OpenerName, HistoryLength, BrowserLanguage, BrowserCountry, SocialNetwork, SocialAction,
    HTTPError, SendTiming, DNSTiming, ConnectTiming, ResponseStartTiming, ResponseEndTiming,
    FetchTiming, SocialSourceNetworkID, SocialSourcePage, ParamPrice, ParamOrderID, ParamCurrency,
    ParamCurrencyID, OpenstatServiceName, OpenstatCampaignID, OpenstatAdID, OpenstatSourceID, UTMSource,
    UTMMedium, UTMCampaign, UTMContent, UTMTerm, FromTag, HasGCLID,
    RefererHash, URLHash, CLID
FROM hits_kudu_raw;
