#!/bin/bash
set -e

sudo apt-get update -y
sudo apt-get install -y python3-pip python3-venv openjdk-17-jdk wget

if [ ! -d myenv ]; then
    python3 -m venv myenv
fi
# shellcheck disable=SC1091
source myenv/bin/activate
pip install -q pyspark==3.5.5 psutil

AURON_JAR_URL='https://github.com/apache/auron/releases/download/v5.0.0/blaze-engine-spark-3.5-release-5.0.0-SNAPSHOT.jar'
if [ ! -f auron.jar ]; then
    wget --continue --progress=dot:giga "$AURON_JAR_URL" -O auron.jar
fi
