#!/bin/bash
set -e

if ! command -v tursodb >/dev/null 2>&1; then
    sudo apt-get update -y
    sudo apt-get install -y curl
    curl --proto '=https' --tlsv1.2 -LsSf \
        https://github.com/tursodatabase/turso/releases/download/v0.6.0-pre.27/turso_cli-installer.sh | sh
fi

export HOME=${HOME:=~}
# shellcheck disable=SC1091
source "$HOME/.turso/env"
