name: "Validate results"

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: python3 validate-results.py
        if: github.event_name != 'pull_request'
      - uses: actions/checkout@v3
        if: github.event_name == 'pull_request'
        with:
          ref: ${{ github.event.pull_request.base.sha }}
          path: .base
      - run: python3 validate-results.py --base .base
        if: github.event_name == 'pull_request'
