#!/bin/bash
set -e

QW_IMAGE="quickwit/quickwit:v0.9.0-rc"

if ! command -v docker >/dev/null 2>&1; then
    sudo apt-get update -y
    sudo apt-get install -y docker.io
fi
sudo apt-get install -y wget curl jq bc

sudo systemctl start docker 2>/dev/null || true
sudo docker pull "$QW_IMAGE"

mkdir -p qwdata
